### ISSUE TITLE
Drop custom script and workflow to update Python dependencies and use Dependabot

### ISSUE THREAD

**Issue by ferrarimarco** [super-linter/super-linter#2579]
Currently, Python dependencies are handled by a [workflow](https://github.com/github/super-linter/blob/main/.github/workflows/deps-python.yml) and a [script](https://github.com/github/super-linter/blob/main/.github/scripts/update-python.sh).

Why don't we drop the custom workflow and script?

PS: I saw there are a script and a workflow to update NPM dependencies as well, but I didn't had a look to those yet.

/cc @lindluni who worked on this implementation IIRC
/cc @admiralAwkbar 

EDIT: updated after realizing that Dependabot handles all the requirements files in /dependencies/python. Example: https://github.com/github/super-linter/network/updates/314377296

**Comment by Hanse00** [comment]
If it turns out there's some reason this is in fact needed, we can revert #4225. But as it stands, these actions are being removed. @zkoppert and I discussed, and neither of us could think of a reason why this action would be needed alongside dependabot.
