### ISSUE TITLE
Superlinter does not find actionlint.yaml in the default location of .github/linters.

### ISSUE THREAD

**Issue by bcollamore** [super-linter/super-linter#2581]
## Describe the bug

Superlinter does not find actionlint.yaml in the default location of .github/linters. (It will find actionlint.yml.)

## Expected behavior

A path of .github/linters/actionlint.yaml should work by default (as well as .github/linters/actionlint.yml)

## Logs

This debug log entry is notable:

GITHUB_ACTIONS language rule file has a secondary rules file name to check (actionlint.**yaml**). Path:[/github/workspace/.github/linters/actionlint.**yml**]

## Additional context

github/super-linter/slim@v4.8.7

At first I was trying to place actionlint.yaml in actionlint's default directory before realizing that superlinter specifies its own default directory.

**Comment by BretFisher** [comment]
For each linter, there is only one default file in super-linter. Any other filename requires setting it as a custom filename. Bash (which super-linter is written in) allows for a default ENV, [which is how it's used here](https://github.com/github/super-linter/blob/main/lib/linter.sh#L103). 

TIP: When I want to use linters as normal in that repo, I just symlink the `.github/linters/` file to the location (and name) it expects.

**Comment by BretFisher** [comment]
I too would love for Super-Linter to support an array of default files for each linter, based on that linters expectations. This would likely be considered a feature request.

**Comment by ferrarimarco** [comment]
This is a fair request, also considering that [YAML recommends using the yaml extension when possible](https://yaml.org/faq.html). I suppose this requires a bit more to generalize to other files as well. I remember that we do this kind of check in various places, and it may be time to refactor and generalize a bit.

**Comment by Hanse00** [comment]
It seems to me like the specific scenario of yml vs. yaml should be addressed by the code at [linterRules.sh#L68-L74](https://github.com/super-linter/super-linter/blob/main/lib/functions/linterRules.sh#L68-L74):

```shell
if [[ $FILE_EXTENSION == 'yml' ]]; then
  # Need to see if yaml also exists
  SECONDARY_FILE_NAME="$FILE_NAME.yaml"
elif [[ $FILE_EXTENSION == 'yaml' ]]; then
  # need to see if yml also exists
  SECONDARY_FILE_NAME="$FILE_NAME.yml"
fi
```

So this is a bug, as we would expect it to handle the scenario.

The more generic suggestion of: We should be able to handle more than one default per language, I agree is a worthwhile suggestion. Tracking that separately in #4222
