### ISSUE TITLE
RunAdditionalInstalls() failing if php extensions not in image

### ISSUE THREAD

**Issue by mattfoster7** [super-linter/super-linter#2714]
## Describe the bug

Composer install is failing when expected PHP extensions are not loaded, for example ext-soap.

The last working version is 4.7.3 which is before the additional `RunAdditionalInstalls()` method was added. All of v4.8.x didn't work because of the PATH issue, which was fixes in v4.9.1 (#2643) but has exposed this new issue with extensions.

In v4.7.3, you did not run composer install, and I ran it as an additional action manually just before the lint, using `php-actions/composer` which allows me to specify extensions.

## Expected behavior

Running composer install should be optional (we can run it as a previous action prior to Lint) or we should be able to specify the PHP extensions used in the image.

## Steps to Reproduce

Try and run PHP_PSALM on a PHP project which requires a package that depends on ext-soap, for example: `googleads/googleads-php-lib`

## Logs

```
2022-03-30 17:42:05 [INFO]   ---------------------------------
2022-03-30 17:42:05 [INFO]   ------ File list to check: ------
2022-03-30 17:42:05 [INFO]   ---------------------------------
2022-03-30 17:42:06 [INFO]   ----------------------------------------------
2022-03-30 17:42:06 [INFO]   Successfully gathered list of files...
2022-03-30 17:42:06 [INFO]   Found PHP files to validate, and [VALIDATE_PHP_PSALM] set to true, need to run composer install
2022-03-30 17:42:06 [INFO]   looking for composer.json in the users repository...
2022-03-30 17:42:07 [INFO]   Found [composer.json] at:[/github/workspace/composer.json]
2022-03-30 17:42:07 [ERROR]   ERROR! Failed to run composer install at location:[/github/workspace]
2022-03-30 17:42:07 [FATAL]   ERROR:[Your lock file does not contain a compatible set of packages. Please run composer update.]
```

**Comment by mattfoster7** [comment]
#2005

**Comment by basilgohar** [comment]
I hate to just ask about this like this, but we've been having this problem for quite some time.  Because PSALM is enabled by default in super-linter, our tests always fail no matter the situation.  I either have to disable PSALM or stop using super-linter altogether to get our statuses to go green at this time.

**Comment by krtrth** [comment]
> I hate to just ask about this like this, but we've been having this problem for quite some time. Because PSALM is enabled by default in super-linter, our tests always fail no matter the situation. I either have to disable PSALM or stop using super-linter altogether to get our statuses to go green at this time.
> 
> Will there be any further action on this issue? As noted above by [mattfoster7](https://github.com/mattfoster7) PSALM has been broken for two whole minor versions of super-linter thus far for different reasons.

I am also getting this same issue how did you fix this ?

**Comment by PonyPete** [comment]
I have this same issue with a standard laravel project

**Comment by krtrth** [comment]
also phpstan is giving issue of composer 
`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.30. in /github/workspace/vendor/composer/platform_check.php on line 24
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.30. in /github/workspace/vendor/composer/platform_check.php on line 24`
i am setting the ubuntu latest environment  and installing the composer after code checkout and that is working fine the phpcs works but stan fails with this error. once I remove installing composer phpstan works but I can't able to recognise framework files or any vendor file

**Comment by ferrarimarco** [comment]
Hi folks! If this keeps happening in the latest Super-linter versions, can you please create a new issue? Thanks!
