### ISSUE TITLE
Group output per linter

### ISSUE THREAD

**Issue by adamralph** [super-linter/super-linter#2755]
**Is your feature request related to a problem? Please describe.**

The output from super-linter is enormous. It's difficult to navigate to the output from a specific linter.

**Describe the solution you'd like**

The output from each linter grouped. For example:

```text
::group::ansible-lint
# ansible-lint output
::endgroup::
::group::cfn-lint
# cfn-lint output
::endgroup::
::group::arm-ttk
# arm-ttk output
::endgroup::

# and so on...

```

which renders in GitHub actions as collapsible sections, similar to:

---

<details>
<summary>ansible-lint</summary>
# ansible-lint output
</details>
<details>
<summary>cfn-lint</summary>
# cfn-lint output
</details>
<details>
<summary>arm-ttk</summary>
# arm-ttk output
</details>

\# and so on...

---

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by bewuethr** [comment]
Or maybe even [Markdown job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) 🤩

**Comment by nvuillam** [comment]
I think you are looking for [MegaLinter](https://megalinter.github.io/latest/) , which has separate log files for each linter output👼

**Comment by ferrarimarco** [comment]
Reference: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
