### ISSUE TITLE
Super- Linter unable to lint only on changed files locally

### ISSUE THREAD

**Issue by shivakumar-os** [super-linter/super-linter#2957]
## Describe the bug

We are using [Super-linter](https://github.com/github/super-linter) GitHub to validate linters verifications and issues in our codebase to report in GitHub actions workflow and in local branch.

## Expected behavior

When we try to run [Super-Linter Docker container](https://github.com/github/super-linter/blob/main/docs/run-linter-locally.md) locally in our branch , super-linter linter applied entire repo level , we followed according to the steps in the above link , applied VALIDATE_ALL_CODEBASE to false to run linter on staged(changed) files , but after applying also showing the same result, linter applying on repo level instead of changed files.

Linters should run on changed files of a repo instead of running it on complete repo level.

## Steps to Reproduce

Below are the docker steps followed to run locally , both resulting the same , linters are applying complete repo level of each files.

 ```bash
    docker run -e RUN_LOCAL=true -e USE_FIND_ALGORITHM=true -v ${PWD}:/tmp/lint github/super-linter                    
    docker run  -e RUN_LOCAL=true -e USE_FIND_ALGORITHM=true -e VALIDATE_ALL_CODEBASE=false -v ${PWD}:/tmp/lint github/super-linter
   ```

## Logs

Tried to run super-linter docker container on changed files and mapped to the directory where file exist

![image](https://user-images.githubusercontent.com/97942229/170254838-2db9cd32-8043-4773-a18f-dcf852a1fde7.png)

In the above screen shot followed steps according to the [Running super-linter locally](https://github.com/github/super-linter/blob/main/docs/run-linter-locally.md) but the linter not able to mount any repository.

## Additional context

what is the correct way to run the super-linter docker container locally to lint only specific changed files ?
We want to validate linters only on changed files in local environment , can yo please provide any steps if we miss anything in above.

**Comment by riosengineer** [comment]
I'm also having this issue when running locally in Azure DevOps - it scans the entire code base regardless of the env var. Any chance there is an ETA on if this may be fixed from the back log at all? With a large code base it can take a while to run

**Comment by ferrarimarco** [comment]
We'll need to revisit this once https://github.com/super-linter/super-linter/pull/4889 gets merged.

**Comment by ferrarimarco** [comment]
Tracking this in #4956
