### ISSUE TITLE
ESLint can't find tsconfig.json

### ISSUE THREAD

**Issue by simonppg** [super-linter/super-linter#3141]
## Describe the bug

eslint can't find tsconfig.json file, where the project hasn't eslint config file,

## Expected behavior

eslint should be able to find tsconfig.json without the need to create a eslint config file

## Logs

This is my file structure, I just have a tsconfig.json, on previous version of superlint it was enough 

![Screenshot from 2022-07-16 12-49-55](https://user-images.githubusercontent.com/3270997/179370144-eebe06ab-c94b-48f9-a71e-9dc403a15888.png)

My tsconfig.json file looks like this:
![Screenshot from 2022-07-16 12-50-29](https://user-images.githubusercontent.com/3270997/179370148-a9fd0804-e09f-40b5-a285-fbb818a40d93.png)

Here is the actual behavior, it can't find the configuration on my tsconfig.json which include those files from `src` folder 
![Screenshot from 2022-07-16 12-48-53](https://user-images.githubusercontent.com/3270997/179370136-8a15ce27-645e-4c5f-8da1-4dacf8c698d5.png)

## Additional context

I want to use the default eslint configuration set up on superlint, I think this should be possible without the need for a eslint config file, please let me know if I'm wrong with this affirmation, but since this was the behavior before, I'm expecting to still have it.

Link to the [failing job](https://github.com/simonppg/music-core/runs/7372661405?check_suite_focus=true), and the project.

if this is not the expected behavior, do you have a workaround?

**Comment by simonppg** [comment]
Not a super-linter bug

**Comment by simonppg** [comment]
I close it because I made changes to docs in another branch and saw the linter passing, :man_facepalming: I forgot eslint only runs when you made changes to code.

Anyways I made a simple change to the code, just to make sure I'm not adding anything that could be generating this error, but the bug is still there.
[like to the failing job](https://github.com/simonppg/music-core/runs/7379076474?check_suite_focus=true)
[and the PR](https://github.com/simonppg/music-core/pull/20)

This are the changes I made, this should not break the linter, in fact this should fix a warning if ts-standard is running, not complaining about a parsing error
![Screenshot from 2022-07-17 10-22-42](https://user-images.githubusercontent.com/3270997/179417411-440a5463-05eb-4840-96bd-afa2a93c743f.png)

```bash
2022-07-17 17:12:06 [INFO]
2022-07-17 17:12:06 [INFO]   ----------------------------------------------
2022-07-17 17:12:06 [INFO]   ----------------------------------------------
2022-07-17 17:12:06 [INFO]   Linting [TYPESCRIPT_ES] files...
2022-07-17 17:12:06 [INFO]   ----------------------------------------------
2022-07-17 17:12:06 [INFO]   ----------------------------------------------
2022-07-17 17:12:06 [INFO]   ---------------------------
2022-07-17 17:12:06 [INFO]   File:[/github/workspace/src/NoteValidator.ts]
2022-07-17 17:12:08 [INFO]    - File:[NoteValidator.ts] was linted with [eslint] successfully
2022-07-17 17:12:08 [INFO]
2022-07-17 17:12:08 [INFO]   ----------------------------------------------
2022-07-17 17:12:08 [INFO]   ----------------------------------------------
2022-07-17 17:12:08 [INFO]   Linting [TYPESCRIPT_STANDARD] files...
2022-07-17 17:12:08 [INFO]   ----------------------------------------------
2022-07-17 17:12:08 [INFO]   ----------------------------------------------
2022-07-17 17:12:08 [INFO]   ---------------------------
2022-07-17 17:12:08 [INFO]   File:[/github/workspace/src/NoteValidator.ts]
2022-07-17 17:12:09 [ERROR]   Found errors in [ts-standard] linter!
2022-07-17 17:12:10 [ERROR]   Error code: 1. Command output:
------
ts-standard: Typescript Standard Style! (https://github.com/standard/ts-standard)
  /github/workspace/src/NoteValidator.ts:0:0: Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/NoteValidator.ts.
The file must be included in at least one of the projects provided. ()
------
```

**Comment by incomingstick** [comment]
This issue should be re-opened. I am running `github/super-linter:latest` and also experiencing this issue.

the `tsconfig.json` file in the root of my project is:
```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "noImplicitAny": false,
        "noEmitOnError": true,
        "removeComments": false,
        "sourceMap": true,
        "module": "ES6",
        "target": "es6",
        "rootDirs": [
            "App/Client/scripts/"
        ]
    },
    "include": [
        "App/Client/scripts/**/*"
    ]
}
```

my `.eslintrc.yml` in the root of my project is:
```yml
---
env:
  es6: true
  browser: true
  node: true

parserOptions:
  project: ["./tsconfig.json"]
  createDefaultProgram: true
```
Yet `super-linter` outputs:
```
Linting [TYPESCRIPT_STANDARD] files...
[INFO]   ----------------------------------------------
[INFO]   ----------------------------------------------
[INFO]   ---------------------------
[INFO]   File:[/builds/WebApp/App/Client/scripts/audio.ts]
[ERROR]   Found errors in [ts-standard] linter!
[ERROR]   Error code: 1. Command output:
------
ts-standard: Standard for TypeScript! (https://github.com/standard/ts-standard)
  /builds/WebApp/App/Client/scripts/audio.ts:0:0: Parsing error: ESLint was configured to run on `<tsconfigRootDir>/App/Client/scripts/audio.ts` using `parserOptions.project`: <tsconfigRootDir>/../../../action/lib/.automation/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting##i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file (null)
------
```
Reading the error output, it looks like it is trying to use ``parserOptions.project`: <tsconfigRootDir>/../../../action/lib/.automation/tsconfig.json` and not the `tsconfig.json` in the root of the project.

I have tried explicitly setting these files via the env vars, but that does not seem to work either:
```yml
TYPESCRIPT_ES_CONFIG_FILE: "./.eslintrc.yml"
TYPESCRIPT_STANDARD_TSCONFIG_FILE: "./tsconfig.json"
```

**Comment by woodconn** [comment]
Well, super linter super frustrated me.

Turns out the ENV variable [LINTER_RULES_PATH](https://github.com/super-linter/super-linter/tree/main#environment-variables) is where you must put the tsconfig.json file... 

And no, it does not work to try and use parserOptions.project in the eslintrc.yml which you also have to put in the LINTER_RULES_PATH ....

By default the LINTER_RULES_PATH is set to .github/linters

Currently the linters for Typescript and Javascript are running BUT the rules I've added in the format do not get applied:
> rules:
>   semi: off
>   spaced-comment: off
I haven't tried passing these as an array or as a json object but maybe that would help?  Lack of good organized documentation has made this a super exercise in frustration....

**Comment by woodconn** [comment]
Aha, I should have been using ES versions and not STANDARD versions for validation, something I hadn't considered....

```
    - name: Run Super Linter
      uses: super-linter/super-linter/slim@v5
      with:
        ignore: |
          **/.vscode/launch.json
      env:
        VALIDATE_ALL_CODEBASE: true # When false, only new or edited files will be parsed for validation (requires full git history Checkout Step).
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: main
        LINTER_RULES_PATH: '.github/linters'
        JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
        TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.yml
        IGNORE_GITIGNORED_FILES: true
        VALIDATE_TYPESCRIPT_ES: true
        VALIDATE_JAVASCRIPT_ES: true
        # VALIDATE_JSON: true
        # VALIDATE_HTML: true
        # for more info see: https://github.com/super-linter/super-linter#environment-variables
```
