### ISSUE TITLE
Linting typescript in subdirectory

### ISSUE THREAD

**Issue by heddendorp** [super-linter/super-linter#3228]
## Describe the bug
When I try to lint typescript in a subdirectory of my repo, the linter is always looking for a tsconfig on the root level which is not present.

## Expected behavior
The linter should use the tsconfig in my sub directory

## Steps to Reproduce

Create a repo with a subdirectory that has a typescript project. Like https://github.com/heddendorp/tumi/tree/feat/linting
Add an eslint config to the subdirectory.
Try to lint the repository.

## Logs

https://github.com/heddendorp/tumi/runs/7804965134?check_suite_focus=true

## Additional context

I would need to somehow set the working directory for the linter to fix this is my guess.

I am happy to provide more information

**Comment by heddendorp** [comment]
I actually think this is an issue and would be glad for some more information

**Comment by ferrarimarco** [comment]
I don't have access to that repository. Can you share an example configuration, and relevant output log, with debug logging enabled?
