### ISSUE TITLE
Replace kubeval with kubeconform

### ISSUE THREAD

**Issue by nmische** [super-linter/super-linter#3496]
**Is your feature request related to a problem? Please describe.**
`kubeval` is no longer supported.

**Describe the solution you'd like**
Replace `kubeval` with `kubeconform` per recommendation in `kubeval`'s [README](https://github.com/instrumenta/kubeval#kubeval). I have been using `kubeconform` in place of `kubeval` for quite some time and it works well.

**Describe alternatives you've considered**
There is also [`kube-linter`](https://github.com/stackrox/kube-linter), but it has slightly more opinionated linting rules than `kubeval`/`kubeconform`.

**Additional context**
This has been requested before: https://github.com/github/super-linter/issues/2460

**Comment by ferrarimarco** [comment]
This was implemented in https://github.com/super-linter/super-linter/pull/3800
