### ISSUE TITLE
Add cmake-format

### ISSUE THREAD

**Issue by malaterre** [super-linter/super-linter#3606]
**Is your feature request related to a problem? Please describe.**

Please add cmake-format. This is a great companion to c++ project 

**Describe the solution you'd like**

integrate with `cmake-format` linter

**Describe alternatives you've considered**

There is a single cmake linter as of today

**Additional context**

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/github/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

**Comment by ferrarimarco** [comment]
It looks like that project is not maintained anymore. Closing :(
