### ISSUE TITLE
Simplify dependency files

### ISSUE THREAD

**Issue by ferrarimarco** [super-linter/super-linter#3727]
**Is your feature request related to a problem? Please describe.**

We currently have transitive dependencies defined in dependency files. I had a quick look at the pip requirements files and we may shorten them a bit. For example, the [ansible-lint requirements file](https://github.com/github/super-linter/blob/main/dependencies/python/ansible-lint.txt) lists transitive dependencies.

This leads to:

- (arguably) higher maintenance burden because we need to take care of more dependencies (more dependabot PRs, more reviews, more builds...)
- Duplicate effort because transitive dependencies should be already handled by the maintainers of each linter that we install.

**Describe the solution you'd like**

1. Remove transitive dependencies from our dependency files.

**Comment by zkoppert** [comment]
I think this is a great idea! Want to open up a PR on this? I'm guessing this would be a change to the script that generates the python dependency files?

**Comment by ferrarimarco** [comment]
You mean this script? https://github.com/super-linter/super-linter/blob/main/.github/scripts/update-python.sh

We don't run this script (and the [npm one](https://github.com/super-linter/super-linter/blob/main/.github/scripts/update-npm.sh)) since https://github.com/super-linter/super-linter/pull/4225

We may want to delete both, actually.

If you mean some other script, can you point me to that? I couldn't find it after a quick search. Thanks!

If we don't have any script to generate said files, we may want to manually prune them once, and that should be enough.

**Comment by zkoppert** [comment]
That was the script I thought we were running but I think you're right. Sounds like we need some manual clean up work here.

**Comment by ferrarimarco** [comment]
Yeah. I can have a look
