### ISSUE TITLE
v4.10.0 shows hundreds of 'fatal: not a git repository' messages.

### ISSUE THREAD

**Issue by KineticTheory** [super-linter/super-linter#3786]
## Describe the bug

After upgrading to `slim-v4.10.0` (January 4, 2023), my pipeline output has over 600 entries of `fatal: not a git repository (or any of the parent directories): .git`.  While not actually fatal to the CI job, these make it more difficult to parse the output.  These messages do not appear when using `slim-v4.9.7`.

## Expected behavior

Unhelpful `fatal` messages that aren't actually fatal should not show up in the pipeline output/log.  

## Steps to Reproduce

* I'm not allowed to run docker locally, so I can't provide a simple reproducer.
* The GitLab CI job specification is:

```yaml
superlinter:
  tags:
    - docker-shared
  stage: lint
  image:
    name: github/super-linter:slim-v4
  script: ["true"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    RUN_LOCAL: "true"
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    ANSIBLE_DIRECTORY: $CI_PROJECT_PATH
    LINTER_RULES_PATH: $CI_PROJECT_PATH/.github/linters
    DEFAULT_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    ERROR_ON_MISSING_EXEC_BIT: "true"
    FILTER_REGEX_EXCLUDE: (.*[.]cc$|/test/)
    PYTHON_FLAKE8_CONFIG_FILE: .flake8
    SUPPRESS_POSSUM: "true"
    LOG_LEVEL: "VERBOSE"
    VALIDATE_ALL_CODEBASE: "false"
    VALIDATE_BASH: "true"
    VALIDATE_BASH_EXEC: "true"
    VALIDATE_DOCKERFILE: "true"
    VALIDATE_ENV: "true"
    VALIDATE_HTML: "true"
    VALIDATE_JSON: "true"
    VALIDATE_LUA: "true"
    VALIDATE_MARKDOWN: "true"
    VALIDATE_PERL: "true"
    VALIDATE_PYTHON: "true"
    VALIDATE_PYTHON_FLAKE8: "true"
    VALIDATE_POWERSHELL: "true"
    VALIDATE_RUBY: "true"
    VALIDATE_SHELL_SHFMT: "true"
    VALIDATE_XML: "true"
```

## Logs

If I use `LOG_LEVEL: "DEBUG"`, the output looks like the following snippet.  Note that I have replaced actual `group/repository` names with placeholders `<group>/<repository>`.

```
2023-01-04 16:14:38 [INFO]   ---------------------------------
2023-01-04 16:14:38 [INFO]   ------ File list to check: ------
2023-01-04 16:14:38 [INFO]   ---------------------------------
2023-01-04 16:14:38 [DEBUG]   File:[/builds/<group>/<repository>/.clang-format], File_type:[clang-format], Base_file:[.clang-format]

fatal: not a git repository (or any of the parent directories): .git

2023-01-04 16:14:38 [DEBUG]   Failed to get filetype for:[/builds/<group>/<repository>/.clang-format]!
2023-01-04 16:14:38 [DEBUG]   
2023-01-04 16:14:38 [DEBUG]   File:[/builds/<group>/<repository>/.clang-tidy], File_type:[clang-tidy], Base_file:[.clang-tidy]

fatal: not a git repository (or any of the parent directories): .git

...

2023-01-04 16:15:18 [DEBUG]   File:[/builds/<group>/<repository>/src/bin/ythi.cc], File_type:[cc], Base_file:[ythi.cc]
2023-01-04 16:15:18 [DEBUG]   FILTER_REGEX_EXCLUDE match. Skipping /builds/<group>/<repository>/src/bin/ythi.cc
2023-01-04 16:15:18 [DEBUG]   File:[/builds/<group>/<repository>/src/bin/ythi.hh], File_type:[hh], Base_file:[ythi.hh]

fatal: not a git repository (or any of the parent directories): .git
```

**Comment by lindluni** [comment]
Hi @KineticTheory

Thank you for raising this bug, I will take a look at it this week!

**Comment by ferrarimarco** [comment]
Might be related to this check: https://github.com/github/super-linter/blob/aad87c569b8a3de467bf6504c06127822e2845aa/lib/functions/buildFileList.sh#L299

**Comment by oorekhov** [comment]
Hi @lindluni 
Did you manage to look into this? I got the same errors when checkout repository to custom path, by setting 'path' option in the checkout action. If this is the reason, is there any way to change working directory? I can't use default checkout path as have multiple depended repos, that needs to be clones into workspace directory.

**Comment by KineticTheory** [comment]
FYI - this is still an issue for my codes.   It doesn't cause the CI check to fail but the clutter in the log isn't great.

**Comment by pvarin-figure** [comment]
Adding the flag `-w /tmp/lint` in my local `docker run` command helped me out. It sets the working directory correctly in the container before running the lint command.

**Comment by choeger** [comment]
I think that issue still persists. Setting the working directory is a workaround.
