### ISSUE TITLE
Add eslint-plugin-compat

### ISSUE THREAD

**Issue by flynnt** [super-linter/super-linter#3980]
**Is your feature request related to a problem? Please describe.**
I use [eslint-plugin-compat](https://www.npmjs.com/package/eslint-plugin-compat) to extend `eslint` in my project, but it doesn't appear that it's available in the image used by `super-linter`. This leads to the following error:

> The package "eslint-plugin-compat" was not found when loaded as a Node module from the directory "/github/workspace".

**Describe the solution you'd like**
If possible, please add `eslint-plugin-compat`. I think it will become more common as people stop using Babel for transpilation.

**Describe alternatives you've considered**
If it's possible to add the dependency manually to the workflow, I suppose I could do that, but according to the `super-linter` docs, that doesn't seem like an option.

**Comment by verymadmax** [comment]
> **Is your feature request related to a problem? Please describe.** I use [eslint-plugin-compat](https://www.npmjs.com/package/eslint-plugin-compat) to extend `eslint` in my project, but it doesn't appear that it's available in the image used by `super-linter`. This leads to the following error:
> 
> > The package "eslint-plugin-compat" was not found when loaded as a Node module from the directory "/github/workspace".
> 
> **Describe the solution you'd like** If possible, please add `eslint-plugin-compat`. I think it will become more common as people stop using Babel for transpilation.
> 
> **Describe alternatives you've considered** If it's possible to add the dependency manually to the workflow, I suppose I could do that, but according to the `super-linter` docs, that doesn't seem like an option.

I've got an error with another plugin. But in general, it's the same issue
![image](https://github.com/github/super-linter/assets/41686731/bfddaa02-03ab-4cd8-b62c-cf9a4f375758)
