### ISSUE TITLE
config file for python black, pylint and isort is not working as expected.

### ISSUE THREAD

**Issue by mariekekortsmit** [super-linter/super-linter#4022]
Hi all,

I'm using super-linter to lint a part of my repository and want to exclude certain folders from python linting only. 

I set up an empty repo to replicate my issues, the structure is as follows:

- src
   - folder1
     - app.py 
   - folder2 
     - app.py   

With in both app.py folders some random python code that will not pass linting for python black, pylint and isort:
```
import sys,os,re
from typing import List

def my_func(arg1: str,arg2: int) -> List[int]:
    result=[i for i in range(arg2) if re.match(arg1,str(i))]
    return result

if __name__ == "__main__":
    print("Hello World")
    print(my_func("a",5))
```

My pyproject.toml file looks like this:
```
[tool.black]
exclude = ["./src/folder1/","./src/folder2/"]

[tool.pylint.MASTER]
ignore = ["./src/folder1/","./src/folder2/"]

[tool.isort]
skip_glob =["./src/folder1/","./src/folder2/"]
```

I'm using super-linter from within a PR validation pipeline in Azure Devops, but to replicate my issue I'm now running super-linter locally with this command:
```
docker run \
            -e IGNORE_GITIGNORED_FILES=true \
            -e LOG_LEVEL=WARN \
            -e RUN_LOCAL=true \
            -e LINTER_RULES_PATH=. \
            -e PYTHON_BLACK_CONFIG_FILE=pyproject.toml \
            -e PYTHON_FLAKE8_CONFIG_FILE=.flake8 \
            -e PYTHON_ISORT_CONFIG_FILE=pyproject.toml \
            -e PYTHON_MYPY_CONFIG_FILE=pyproject.toml \
            -e PYTHON_PYLINT_CONFIG_FILE=pyproject.toml \
            -v ~/lintertest:/tmp/lint \
            github/super-linter:v4
```
But while I am excluding both app.py files from pythonl inting by means of the pyproject.toml config file, it still picks up the issues in those files:
```
2023-03-21 09:04:36 [ERROR]   ERRORS FOUND in PYTHON_BLACK:[2]
2023-03-21 09:04:36 [ERROR]   ERRORS FOUND in PYTHON_PYLINT:[2]
2023-03-21 09:04:36 [ERROR]   ERRORS FOUND in PYTHON_ISORT:[2]
```

If I use e.g. python black outside of superlinter with this config file by running `black --config=pyproject.toml .` it does actually skip the folders as expected. 

What is going wrong here?

**Comment by avadhanij6si** [comment]
Have you tried using `FILTER_REGEX_INCLUDE` and `FILTER_REGEX_EXCLUDE` env variables?
