### ISSUE TITLE
Variable "GITHUB_ACTIONS_COMMAND_ARGS", missing docs on how to use it, got an error

### ISSUE THREAD

**Issue by neilime** [super-linter/super-linter#4023]
## Describe the bug

By exploring code, I can found the variable "GITHUB_ACTIONS_COMMAND_ARGS". but I didn't succeed to use it.

## Expected behavior

Be able to define custom actionlint args without error

## Steps to Reproduce

```shell
docker run \
  -e RUN_LOCAL=true \
  -e ACTIONS_RUNNER_DEBUG=true \
  -e DISABLE_ERRORS=false \
  -e ERROR_ON_MISSING_EXEC_BIT=true \
  -e LINTER_RULES_PATH=. \
  -e MULTI_STATUS=false \
  -e VALIDATE_ALL_CODEBASE=true \
  -e GITHUB_ACTIONS_COMMAND_ARGS="-ignore 'is not defined in object type'" \
  -v $(pwd):/tmp/lint \
  ghcr.io/github/super-linter:slim-v4
```

Got the error: 

```
 [ERROR]   Error code: 3. Command output:
------
could not read "in": open in: no such file or directory
------
```

**Comment by mdsakalu** [comment]
This seems to be something related to subshells and/or shell expansions within `lib/functions/worker.sh`.

For me, this did not work:
```
-e GITHUB_ACTIONS_COMMAND_ARGS="-ignore ':info:' -ignore ':style:'"
```

But this did work:
```
-e GITHUB_ACTIONS_COMMAND_ARGS="-ignore :info: -ignore :style:"
```

Obviously this isn't helpful if your `ignore` regex needs to be within quotes. Ideally, all options could be specified in the `actionlint.yml` config file so that we don't have to rely on command line args. That's how most of the other linters behave. cc @rhysd

**Comment by neilime** [comment]
Sadly, *actionlint* does support "ignore" option, and with GITHUB_ACTIONS_COMMAND_ARGS we cannot pass multiple words like `GITHUB_ACTIONS_COMMAND_ARGS="-ignore undefined variable"`, neither single or double quotes.

It is pretty complicated to use this linter with these limitations

**Comment by iownthegame** [comment]
linked PR: https://github.com/github/super-linter/pull/3772

**Comment by yermulnik** [comment]
Just found myself in the same pitfall as topicstarter =(
Are there any guidelines on how to correctly pass `-ignore 'some error message'`?
Looking at https://github.com/super-linter/super-linter/pull/3772/files I'm wondering what's the value of `GITHUB_ACTIONS_LINTER_RULES`? I couldn't find its definition using GH search in this repo =(

**Comment by yermulnik** [comment]
@lindluni FYI
Seems like the way `GITHUB_ACTIONS_COMMAND_ARGS` value is passed in just breaks this functionality by splitting all elements of the value by whitespace/IFS chars.
Could this issue please be re-open and worked on or should I better open new issue for this?
Thanks

**Comment by akefirad** [comment]
I'd suggest to update the docs so that people don't spend time troubleshooting why it's not working. Happy to send a PR. LMK.

**Comment by ferrarimarco** [comment]
We don't have a special case for actionlint:

https://github.com/super-linter/super-linter/blob/5a8805dc4fb3ff22315a0c7f8ce8d3cc7da81958/lib/functions/worker.sh#L339-L342

So it should run the command as specified in:

https://github.com/super-linter/super-linter/blob/5a8805dc4fb3ff22315a0c7f8ce8d3cc7da81958/lib/linter.sh#L894-L898

If you enable debug logging (set `ACTIONS_RUNNER_DEBUG=true`), what is the output of the following log line for actionlint ?

https://github.com/super-linter/super-linter/blob/5a8805dc4fb3ff22315a0c7f8ce8d3cc7da81958/lib/functions/worker.sh#L77
