### ISSUE TITLE
deprecation warning when linting terraform file with tflint

### ISSUE THREAD

**Issue by B-Souty** [super-linter/super-linter#4108]
## Describe the bug

The way super-linter runs tflint will be deprecated in the near future. Getting a warning from tflint when running the action.

```
 WARNING: "tflint FILE/DIR" is deprecated and will error in a future version. Use --chdir or --filter instead.
```

## Expected behavior

I expect tflint to run without deprecation warning

## Steps to Reproduce

create a .tf file and run the super-linter

## Logs

```
WARNING: "tflint FILE/DIR" is deprecated and will error in a future version. Use --chdir or --filter instead.
```

## Additional context

I'm not sure what would be the best solution to fix this.

Instead of gathering a list of file and passing each one of them individually to tflint maybe we could have the option to run recursively but I guess then you lose the option to run only on changed file.

**Comment by zkoppert** [comment]
we could also consider deprecating tflint and remove it from the super-linter all together. Not my preferred option but Thought I'd call that out anyways.

**Comment by zkoppert** [comment]
@anthonyolo I believe you are correct. Cutting a new release now.

**Comment by zkoppert** [comment]
resolved via https://github.com/super-linter/super-linter/releases/tag/v5.2.0
