### ISSUE TITLE
pulling the super linter docker image is taking long time even if we use slim image (around one and half min). tried caching the image but size of the image is too long and for restoring the image also taking long time.  Is there any way to improve the time?

### ISSUE THREAD

**Issue by pratrajesh** [super-linter/super-linter#4186]

**Comment by pratrajesh** [comment]
Any update on this issue

**Comment by zkoppert** [comment]
👋🏻 Hi @pratrajesh. Are you using the super-linter locally or as an action? If as an action, is it self hosted runners or github hosted?

**Comment by pratrajesh** [comment]
> 👋🏻 Hi @pratrajesh. Are you using the super-linter locally or as an action? If as an action, is it self hosted runners or github hosted?

I am using as an action. I tried both self hosted and github hosted runners. As the size of the image is more(both standard and slim) it is taking so much time to pull.

**Comment by zkoppert** [comment]
If using on a self hosted runner, I believe that you can download the image onto that run and use that image. Have you tried that? I'll see if I can dig up some documentation on how to do that.

**Comment by pratrajesh** [comment]
@zkoppert  That helps.

We are using organization level Github runners. Runners will be allocated dynamically and it is not recommended to download the image on all the runners as it will be shared to other workflows also.

**Comment by pratrajesh** [comment]
@zkoppert 

I want to lint only openapi specification files only. Is there any better way to lint openapi sepcs?.

**Comment by zkoppert** [comment]
Yeah, If you aren't trying to lint multiple languages, super-linter may not be the best fit for your project. You may try https://github.com/IBM/openapi-validator
