### ISSUE TITLE
Additional Package (Next and Turbo) Support

### ISSUE THREAD

**Issue by ChrisPage-AT** [super-linter/super-linter#4349]
**Is your feature request related to a problem? Please describe.**
I'm trying to use Super-Linter on a repo that uses Vercel's Next.js and Vercel's Turbo.  These do not exist on the super-linter base image, and I cannot find a way to add them manually.  This causes eslint to throw errors about missing packages.

**Describe the solution you'd like**
It would be most convenient if support for these packages could be added to the super-linter base image.  I can even make a PR for this, if it's as simple as adding the packages to the [package.json](https://github.com/super-linter/super-linter/blob/main/dependencies/package.json) file.

**Describe alternatives you've considered**
A more general solution would be to add a parameter to super-linter itself, allowing it to install packages after the image downloads.  Something like `ADDITIONAL_JS_PACKAGES` would work I think, but I'm not sure what kind of internal changes would need to happen for that.

**Comment by ChrisPage-AT** [comment]
I've made a PR for this, but I don't know who to ask to review it.  It's a very simple change, so hopefully it doesn't take too long to review.

**Comment by ChrisPage-AT** [comment]
This is the PR: https://github.com/super-linter/super-linter/pull/4446

**Comment by zkoppert** [comment]
closed via https://github.com/super-linter/super-linter/pull/4446
