### ISSUE TITLE
External ruleset not picked up by super linter

### ISSUE THREAD

**Issue by jayanthpatki91** [super-linter/super-linter#4376]
## Describe the bug

I am trying to reference external ruleset in my swagger.yml in GitHub action using the http url as per the doc:
https://docs.stoplight.io/docs/spectral/83527ef2dd8c0-extending-rulesets

But it wont work.

## Expected behavior

workflow should recognize and pick up external rule file , given the http url of the rule file

## Steps to Reproduce

Refer external linter rule file with http url using GitHub actions with Super Linter as per stoplight spectral documentation

**Comment by ferrarimarco** [comment]
@jayanthpatki91 can you please share more information about how you're running super-linter in your repository?
