### ISSUE TITLE
Don't hardcode major version in release builds

### ISSUE THREAD

**Issue by Hanse00** [super-linter/super-linter#4419]
The release workflow currently hardcodes that the release should be tagged as `v5` as well as the more granular minor and patch version. For now this is not a problem, but eventually we may have another major version, and having to remember to update this value might bite us.

https://github.com/super-linter/super-linter/blob/main/.github/workflows/release.yml#L87

We should find a way to ensure this value is inserted dynamically.

**Comment by zkoppert** [comment]
PR opened for this one at https://github.com/super-linter/super-linter/pull/4441
