### ISSUE TITLE
v5.1.0 not working due to unauthorized daemon

### ISSUE THREAD

**Issue by HorizonNet** [super-linter/super-linter#4423]
## Describe the bug

When Dependabot provides an update from 5.0.0 to 5.1.0 the build is failing with the error message provided in the logs below. Same also seems to happen when trying to stay on 5.0.0. Please note that the upgrade from github/super-linter to super-linter/super-linter has been done in the past. Still, 5.0.0 seems to work when using github/super-linter instead of super-linter/super-linter.

## Expected behavior

Switch to 5.1.0 without a problem and a working 5.0.0 version, independent of the actual image (github or super-linter).

## Steps to Reproduce

Running a super-linter action with super-linter/super-linter in version 5.0.0 or 5.1.0.

## Logs

```
Pull down action image 'ghcr.io/super-linter/super-linter:v5.0.0'
  /usr/bin/docker pull ghcr.io/super-linter/super-linter:v5.0.0
  Error response from daemon: Head "https://ghcr.io/v[2](xxx/actions/runs/5442982929/jobs/9898918501?pr=1470#step:2:2)/super-linter/super-linter/manifests/v5.0.0": unauthorized
  Warning: Docker pull failed with exit code 1, back off 1.126 seconds before retry.
  /usr/bin/docker pull ghcr.io/super-linter/super-linter:v5.0.0
  Error response from daemon: Head "https://ghcr.io/v2/super-linter/super-linter/manifests/v5.0.0": unauthorized
  Warning: Docker pull failed with exit code 1, back off 6.[4](xxx/actions/runs/5442982929/jobs/9898918501?pr=1470#step:2:4)46 seconds before retry.
  /usr/bin/docker pull ghcr.io/super-linter/super-linter:v[5](xxx/actions/runs/5442982929/jobs/9898918501?pr=1470#step:2:5).0.0
  Error response from daemon: Head "https://ghcr.io/v2/super-linter/super-linter/manifests/v5.0.0": unauthorized
Error: Docker pull failed with exit code 1
```

## Additional context

I did not try v5.1.0 with github/super-linter as I would expect that this gets closed down soon. In some cases super-linter/super-linter seems to make a redirect to github/super-linter when pulling the image (at least for v5.0.0).

**Comment by zkoppert** [comment]
Thanks for submitting this bug report. I will work on a release to fix this issue.

**Comment by zkoppert** [comment]
I believe I have resolved this in v5.1.1. Are you able to confirm @HorizonNet?

**Comment by HorizonNet** [comment]
@zkoppert Thanks for picking this one up. I would say it is not resolved. For one of the Dependabot updates it worked, but directly afterwards I'm getting the following error in several repositories

```
Pull down action image 'ghcr.io/super-linter/super-linter:v5'
  /usr/bin/docker pull ghcr.io/super-linter/super-linter:v5
  Error response from daemon: Head "https://ghcr.io/v[2](xxx/actions/runs/5452044754/jobs/9919018129?pr=2085#step:2:2)/super-linter/super-linter/manifests/v5": unauthorized
  Warning: Docker pull failed with exit code 1, back off 9.074 seconds before retry.
  /usr/bin/docker pull ghcr.io/super-linter/super-linter:v5
  Error response from daemon: Head "https://ghcr.io/v2/super-linter/super-linter/manifests/v5": unauthorized
  Warning: Docker pull failed with exit code 1, back off 8.[5](xxx/actions/runs/5452044754/jobs/9919018129?pr=2085#step:2:5)81 seconds before retry.
  /usr/bin/docker pull ghcr.io/super-linter/super-linter:v5
  Error response from daemon: Head "https://ghcr.io/v2/super-linter/super-linter/manifests/v5": unauthorized
Error: Docker pull failed with exit code 1
```

So, it's similar to the previous message, but now tries to go onto the general tag for the main version. Note that this happens on the pull requests, where I'm trying to update super-linter, as well on all other pull requests on these repositories, independent which super-linter version I'm on (5.0.0, 5.1.0, 5.1.1).

I'm also not sure if using the general tag for the main version should be the case if I'm pinning the version on the exact version.

**Comment by HorizonNet** [comment]
BTW, I'm not sure if that's really a problem with super-linter itself and more with the actual release. According to the issues #4439 and #4444 I would rather guess that artifacts are not getting pushed/deployed.

**Comment by zkoppert** [comment]
@HorizonNet You are correct, this seems closely tied to #4444 . I have set up a new repository as a under a new github account that has no special permissions related to super-linter and it seems to be working now since I made the super-linter package settings public. Can you give it another go?

**Comment by HorizonNet** [comment]
Looks good. I'm currently going through all updates, but a few are already working. Thanks for looking into it. Going to close this one.

BTW, I noticed that tag v5 is used instead of the declared v5.1.1. Not sure if that leads to a problem in future versions if you're not on the latest version. But that's probably something for a future issue if it really pops up.
