### ISSUE TITLE
Support .golangci.yml config file for Golang linter

### ISSUE THREAD

**Issue by razo7** [super-linter/super-linter#4430]
**Is your feature request related to a problem? Please describe.**
I run `super-linter` locally with the Go linter `golangci-lint` and I want it only enable specific linters, e.g., `golangci-lint run --disable-all --enable typecheck`. ATM the linter is running as follows ["golangci-lint run --fast -c ${GO_LINTER_RULES}"](https://github.com/github/super-linter/blob/main/lib/linter.sh#L919), and I would like to modify it so the user can decide which linters to use.

**Describe the solution you'd like**
Having an environment variable VALIDATE_GO_CONFIG that would point to .golangci.yml will enable us running the golangci-lint` with all the customization that a developer needs. 

**Describe alternatives you've considered**
I haven't thought further than above, since I have seen other linters have config file so I assume adding another environment variable for golang linter wouldn't be a burden. See similar issue https://github.com/super-linter/super-linter/issues/1643 where the PHP linter has been modified.

**Additional context**
What is the value of GO_LINTER_RULES from above command?
It would be even better if we could decide whether to use `--fast` when we run golangci-lint with super-linter
This issue is relevant for  https://github.com/super-linter/super-linter/issues/3596 as well

**Comment by zkoppert** [comment]
Hi! This looks like a good idea to me. As you mentioned in your email, feel free to go ahead and get a pull request started for this.

**Comment by HatsuneMiku3939** [comment]
Hello

The current `super-linter` runs to follow the `.github/linters/.golangci.yml` file in the source repository. (if exists)
If we configure `.github/linters/.golangci.yml` as follows:

```yaml
linters:      
  disable-all: true      
  enable:      
    - typecheck 
```

we will achieve the same result as running `golangci-lint run --disable-all --enable typecheck`.

With this configuration, the issue will be be resolved.

**Comment by ferrarimarco** [comment]
#4430 took care of this. We don't add any command switch when linting Go modules. We add `--fast` when linting individual files because that's needed in that case.
