### ISSUE TITLE
shellcheck linter reports an error when there are only warning and info messages

### ISSUE THREAD

**Issue by dean-hpe** [super-linter/super-linter#4472]
If shellcheck gives 2 warnings and 1 info message when linting a bash file it reports that the bash file has an error.  Warnings are not errors. 

2023-07-12 20:17:33 [INFO]   Linting [BASH] files...
2023-07-12 20:17:33 [INFO]   ----------------------------------------------
2023-07-12 20:17:33 [INFO]   ----------------------------------------------
2023-07-12 20:17:33 [INFO]   ---------------------------
2023-07-12 20:17:33 [INFO]   File:[/github/workspace/bin/run_karate_image.sh]
2023-07-12 20:17:33 [ERROR]   Found errors in [shellcheck] linter!
2023-07-12 20:17:33 [ERROR]   Error code: 1. Command output:
------

In /github/workspace/bin/run_karate_image.sh line 50:
CMD="docker run --net=host $tokenenv $hostenv $portenv $dynenv  --rm -t -v $PWD:/project $IMAGE:$VERSION bash -c \"cd /project && java $configpath -jar /karate.jar -T $PARALLEL -o $output_dir -f junit:xml $features $TAGS\""
                                                                                                        ^-----------------------------^ SC20[89](https://github.com/hpe-hcss/scim-proxy-services/actions/runs/5536030567/jobs/10103147178#step:4:90) (warning): Quotes/backslashes will be treated literally. Use an array.

In /github/workspace/bin/run_karate_image.sh line 51:
echo $CMD | bash
     ^--^ SC20[90](https://github.com/hpe-hcss/scim-proxy-services/actions/runs/5536030567/jobs/10103147178#step:4:91) (warning): Quotes/backslashes in this variable will not be respected.
     ^--^ SC2086 (info): Double quote to prevent globbing and word splitting.

**Comment by troyane** [comment]
Is there any update on this? If it is all about the strict checks, is there a way to disable it?

**Comment by ferrarimarco** [comment]
Hi @troyane !

You can set the Shellcheck severity with the `BASH_SEVERITY` environment variable. If you don't set it, shellcheck uses [its default](https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md).

See the super-linter README for details.

**Comment by troyane** [comment]
@ferrarimarco thanks a lot! It was a bit unintuitive that the default value for severity is `style`.
