### ISSUE TITLE
Is the slim image no longer being updated?

### ISSUE THREAD

**Issue by grahame-student** [super-linter/super-linter#4494]
When transitioning over to using reusable workflows I noticed that the slim super-linter version I'd pinned didn't match the pulled docker image.

From my ```lint.yml``` file
```uses: super-linter/super-linter/slim@v5.1.1```

From my workflow logs
![image](https://github.com/super-linter/super-linter/assets/57143548/741e684e-f1de-4263-be31-fee567aebedf)

Note
v5.1.1 vs v5.0.0

Additionally the slim version of the action.yml is still referencing the old github/super-linter repo and not the newer super-linter/super-linter repo

**Comment by Hanse00** [comment]
This looks like an omission to me, not a purposeful change. Thanks for spotting it!

**Comment by bewuethr** [comment]
Looks like this wasn't updated:

https://github.com/super-linter/super-linter/blob/1d0a3be3148306fb8e2b14100c84c567baed990e/slim/action.yml#L7
