### ISSUE TITLE
Update to work with LLVM 14 for Clang Format 14

### ISSUE THREAD

**Issue by ThatTallGuy14** [super-linter/super-linter#4496]
**Is your feature request related to a problem? Please describe.**
Trying to automate adding a space between function definitions which is only available in Clang Format 14 - see SeparateDefinitionBlocks  in https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options 

**Describe the solution you'd like**
Update the super linter to work with clang format 14

**Describe alternatives you've considered**
None

**Additional context**
None

**Note**

**Comment by grahame-student** [comment]
I had a look at the repo used to generate the clang-format docker image: https://github.com/Awkbar-DevOps/clang-format, the Dockerfile has a constant for the LLVM version to use during the build and a quick fork / mod and build later I had a container that ,at the very least, was based on LLVM 17.0.4.

I can't speak towards the generated container's functionality though as I don't have access the the full CI/CD chain from the parent repo.

I would be willing to raise an initial PR to bump the LLVM version for said repo but I don't know if @admiralAwkbar is still actively maintaining it.
