### ISSUE TITLE
The slim metadata file doesn't reference the latest release

### ISSUE THREAD

**Issue by bewuethr** [super-linter/super-linter#4564]
## Describe the bug

The `action.yml` file for the slim version of the action doesn't reference the latest release (currently 5.2.1):

https://github.com/super-linter/super-linter/blob/a797192e187c3bf84749ded4012d264da52556a6/slim/action.yml#L5-L7

## Expected behavior

The release on the slim action corresponds to the rest of the repo

## Steps to Reproduce

Run a [workflow using v5.2.1-slim](https://github.com/bewuethr/workflows/blob/8f5ff4315c85616e395deb0322b32566edbeb362/.github/workflows/linter.yml#L85), and observe that it [pulls image version v5.2.0](https://github.com/bewuethr/workflows/actions/runs/5880340665/job/15946408455#step:2:1).

## Logs

See [here](https://github.com/bewuethr/workflows/actions/runs/5880340665/job/15946408455#step:2:1)

**Comment by fdanielsen** [comment]
Sorry if I should have created a new issue for this, but I just tried running av workflow with slim v5.2.1 and GitHub still pulls the 5.2.0 version of the image. Am I doing something wrong then?

Task has a simple step:
```yaml
- name: Lint Code Base
  uses: super-linter/super-linter/slim@v5.2.1
```

Here's the output from GitHub's action runner:
![image](https://github.com/super-linter/super-linter/assets/343098/7cf22e24-e374-4734-8651-95a57dc06c24)

**Comment by bewuethr** [comment]
Isn't that behaviour potentially unexpected? When I pin super-linter/slim to v5.2.2, it'll fetch the slim-v5 image, which is going to be some more recent version than v5.2.2 in the future, no?

**Comment by zkoppert** [comment]
Hey @bewuethr, I've created a new issue to track that concern. https://github.com/super-linter/super-linter/issues/4650
