### ISSUE TITLE
.textlintrc terminology rule being ignored

### ISSUE THREAD

**Issue by smokedlinq** [super-linter/super-linter#4566]
## Describe the bug

I have a `.textlintrc` file with the following config:

```json
{
  "filters": {
    "comments": true
  },
  "rules": {
    "terminology": {
      "exclude": [
        "id",
        "IDS"
      ]
    }
  }
}
```

The `id` and `IDS` exclude values are being ignored.

## Expected behavior

Usage of `id` and `IDS` would not produce errors.

## Steps to Reproduce

```
docker run --rm -e RUN_LOCAL=true -e VALIDATE_ALL_CODEBASE=true --env-file './.github/super-linter.env' -v .:/tmp/lint ghcr.io/super-linter/super-linter:v5
```

## Logs

```
26:1  ✓ error  Incorrect usage of the term: “id”, use “ID” instead  terminology
57:32   ✓ error  Incorrect usage of the term: “IDS”, use “IDs” instead  terminology
```

## Additional context

I may not understand how to correctly use the config, but from what I currently understand this is the right way to exclude terms right?

**Comment by smokedlinq** [comment]
See that last bit was it, I just misunderstood the exclude property, it's not the word to exclude, it's the term from their termset.

This works:

```json
{
  "filters": {
    "comments": true
  },
  "rules": {
    "terminology": {
      "exclude": [
        "ID",
        "id['’]?s"
      ]
    }
  }
}
```

**Comment by KingBain** [comment]
This drove me UP.THE.WALL


to add to @smokedlinq  answer. 

when you exclude terms, its not just the term its the pattern. 

```text
   /github/workspace/README.md
    26:86  ✓ error  Incorrect term: “Life Cycle”, use “lifecycle” instead  terminology
    33:4   ✓ error  Incorrect term: “Github”, use “GitHub” instead         terminology
    36:67  ✓ error  Incorrect term: “github”, use “GitHub” instead         terminology
    49:54  ✓ error  Incorrect term: “NPM”, use “npm” instead               terminology
```

to skip over Life Cycle and NPM, I had to lookup the pattern used in 

https://github.com/sapegin/textlint-rule-terminology/blob/master/terms.jsonc

and then use that for my exclude list 
```

{
  "filters": {
    "comments": true
  },
  "rules": {
    "terminology" : {
      "defaultTerms": true,
      "exclude": [
        "life[- ]cycle",
        "(?<=(?:\\w+[^.?!])? )npm\\b"
      ]
    }
  }
}
```
