### ISSUE TITLE
The super-linter/super-linter docker image does't exist 

### ISSUE THREAD

**Issue by Robert-96** [super-linter/super-linter#4587]
## Describe the bug

Running the code example from the [Run Super-Linter locally to test your branch of code](https://github.com/super-linter/super-linter/blob/main/docs/run-linter-locally.md) fails with the following error: 

```
$ docker run --rm \                                                  
    -e RUN_LOCAL=true \
    --env-file ".github/super-linter.env" \
    -v "$PWD":/tmp/lint super-linter/super-linter:v5
Unable to find image 'super-linter/super-linter:v5' locally
docker: Error response from daemon: pull access denied for super-linter/super-linter, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

## Expected behavior

There should be a new docker image named `super-linter/super-linter`, or the examples should be updated to use the old one (`github/super-linter`).

## Steps to Reproduce

Follow the steps for: [Run Super-Linter locally to test your branch of code](https://github.com/super-linter/super-linter/blob/main/docs/run-linter-locally.md).

**Comment by s-diez** [comment]
The image exists on ghcr.io therefore `docker run --rm ... ghcr.io/super-linter/super-linter` should work.
