### ISSUE TITLE
Need to format the super-linter log output

### ISSUE THREAD

**Issue by dkumar1989** [super-linter/super-linter#4628]
Hi,

We are running super-linter docker image on Azure DevOps Microsoft hosted agent and linting is happening fine. But we need to format the output of super-linter execution and export these logs outside the agent.

We will try to create a dashboard for the issues that linter is checking.

Is there a way of doing it ?

**Comment by zkoppert** [comment]
I'm not familiar with exporting the docker image log on a Azure DevOps Microsoft hosted agent.
