### ISSUE TITLE
Local Docker environment vars not all working

### ISSUE THREAD

**Issue by dominicmeyer** [super-linter/super-linter#4630]
## Describe the bug

Some of passed variables seem to be not working. RUN_LOCAL is working, because otherwise it would be working at all.
But IGNORE_GITIGNORED_FILES and CREATE_LOG_FILE are not working, because there is always a log file being created.

## Expected behavior

Working flags and in this case no log file.

## Steps to Reproduce

Run:

```bash
docker pull github/super-linter:v4.9.0
docker run --rm \ 
-e RUN_LOCAL='true' \ 
-e USE_FIND_ALGORITHM='true' \ 
-e IGNORE_GITIGNORED_FILES='true' \ 
-e LOG_LEVEL='WARN' \
-e CREATE_LOG_FILE='false' \
-v ./:/tmp/lint \
github/super-linter:v4.9.0
```

**Comment by zkoppert** [comment]
We should probably verify that this is still an issue in the latest version of the super linter (v5.2.1)

**Comment by dominicmeyer** [comment]
Okay, yeah, then I know what the issue is.
I can't use the latest Version because of this: https://github.com/super-linter/super-linter/issues/4445#issue-1788167778

But with the latest version my issue doesn't exist, so maybe it was fixed previously.
