### ISSUE TITLE
no merge base - fatal error

### ISSUE THREAD

**Issue by kpmg-bengmoody** [super-linter/super-linter#4632]
Hello, 

I am currently running super-linter via marketplace action on Github Actions.  The trigger in this particular workflow is a push to a feature branch.  This branch is a direct relative of main.  My plan is for the first job to run some automated testing, including the linting to check changed files for formatting and errors etc.  My problem is I am receiving this following error:
![image](https://github.com/super-linter/super-linter/assets/128812088/d3e35d04-7f6f-4ff0-830d-7f766571d144)

I have googled this error but am unable to find anything specifically relating to super-linter.  I understand this is a general Github error but I am struggling to see why this is being invoked since this feature branch is directly related to main.

For reference, I am using the following inputs:
<img width="404" alt="image" src="https://github.com/super-linter/super-linter/assets/128812088/3d25e378-cdc8-410d-adc8-bd24dec1a720">

I have previously tried changing default_branch and this does seem to get rid of the error but I am unsure as to whether this is the most appropriate move, as surely this is only a 'default' branch, and that the software is capable of automatically adjusting the scenario when running in other branches.  

For reference, the software runs without error on the other trigger I have, which is a push to main (i.e. a merged pull request).  

Any advice will be most welcome.

**Comment by zkoppert** [comment]
Thanks for opening this and providing all the info. Can you let me know what your checkout step looks like where it checks out the code for your repo? Do you specify fetch depth there? I'm wondering if this error might be because your workflow has only done a shallow checkout and doesn't have access to see the commit it is looking for.

**Comment by kpmg-bengmoody** [comment]
hi there
Yes I am just using a very minimal checkout step currently:
```
- name: Checkout repo
              uses: actions/checkout@v3
```

do I need to add some further inputs to this market place action?
or is this action not compatible with super linter?

**Comment by kpmg-bengmoody** [comment]
Right I can see now
![image](https://github.com/super-linter/super-linter/assets/128812088/a429d006-1420-4911-aec4-7625d0e2c365)
This could well be the answer.  I shall give this a try and get back if it is not helping.

**Comment by kpmg-bengmoody** [comment]
seems to have done the job, thank you very much
