### ISSUE TITLE
Run python linter with python2

### ISSUE THREAD

**Issue by HarshadDGhorpade-eaton** [super-linter/super-linter#4652]
I think the linter by default uses python3 to lint files and gives findings accordingly.
we have a project which needs python2.7 specifically, is it possible to configure linter to run using python2 ?

with current run we're getting issues(F821 undefined name) with functions like `xrange` which is not available in python3 anymore.

**Comment by zkoppert** [comment]
This would take setting up a special option in the super-linter action. I don't foresee anyone taking on this work as Python 2 has been deprecated for some time now.
