### ISSUE TITLE
Superlinter how do I set jscpd duplicate threshold

### ISSUE THREAD

**Issue by dean-hpe** [super-linter/super-linter#4770]
I'm getting this error from the superlinter.  It says the threshold is set to 0%.  Where do I set the threshold value?

HTML report saved to report/html/
Markdown report saved to report/jscpd-report.md
ERROR: jscpd found too many duplicates (13.19%) over threshold (0%)
Error: ERROR: jscpd found too many duplicates (13.19%) over threshold (0%)
    at ThresholdReporter.report (/node_modules/@jscpd/finder/dist/reporters/threshold.js:12:19)
    at /node_modules/@jscpd/finder/dist/in-files-detector.js:82:26
    at Array.forEach (<anonymous>)
    at /node_modules/@jscpd/finder/dist/in-files-detector.js:81:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-

**Comment by nantiferov** [comment]
I guess you should create `.jscpd.json` file in `.github/linters` path and define custom threshold there, [docs](https://github.com/kucherenko/jscpd/tree/master/packages/jscpd#config-file)

P.S. It's better to put error messages in code blocks, like this (remove \ from example)

```code
\```
error message
\```
```
