### ISSUE TITLE
Support use-case: lint before `git add`

### ISSUE THREAD

**Issue by hepcat72** [super-linter/super-linter#4774]
**Is your feature request related to a problem? Please describe.**

I usually use a bash function to add and commit all changed and new (and deal with deleted) files, and before I run it, I run super-linter locally on just those changed and new files.  And I just realized why the github superlinter action often finds issues that weren't revealed locally.  It's because it doesn't check untracked files.

**Describe the solution you'd like**

It would be nice/convenient if there was a way to tell superlinter to check untracked files (that are not git ignored).

**Describe alternatives you've considered**

I know I could probably split up my add and commit actions to add the new files before linting, but I've been using this workflow for years.  I do include running isort and black on the new files before running superlinter in my `lint.sh` script, so it's not a common occurrence to encounter discrepancies, so if there's no option to make superlinter check untracked files, I probably won't do anything differently and just occassionally encounter new linting errors from the github actions.

**Additional context**

I'm basing my assumption that superlinter only checks added files on the absence of a file in the `File list to check:` output:
```
2023-10-18 17:08:28 [INFO]   ---------------------------------
2023-10-18 17:08:28 [INFO]   ------ File list to check: ------
2023-10-18 17:08:28 [INFO]   ---------------------------------
2023-10-18 17:08:33 [INFO]   ----------------------------------------------
2023-10-18 17:08:33 [INFO]   Successfully gathered list of files...
2023-10-18 17:08:36 [INFO]   ----------------------------------------------
2023-10-18 17:08:36 [INFO]   ----------------------------------------------
2023-10-18 17:08:36 [INFO]   The script has completed
2023-10-18 17:08:36 [INFO]   ----------------------------------------------
```
when I run superlinter like this:
```
docker run --pull=always -e 'FILTER_REGEX_INCLUDE=(DataRepo\/models\/msrun_sequence\.py)' -e LINTER_RULES_PATH=/ -e IGNORE_GITIGNORED_FILES=true -e RUN_LOCAL=true -v /Users/rleach/PROJECT-local/TRACEBASE/tracebase/:/tmp/lint github/super-linter:slim-v4.9.4
slim-v4.9.4: Pulling from github/super-linter
```
where the _new_ file **`DataRepo/models/msrun_sequence.py`** was specified in `FILTER_REGEX_INCLUDE`.

**Note**
If this is a request to add a new language, after submitting this issue check out [the wiki](https://github.com/super-linter/super-linter/wiki/Adding-new-language-support) for more info on how to accomplish that.

**Comment by kftsehk** [comment]
check git pre-commit/pre-push hook?
a shell script under `.githook` and need some git command to activate it each time for a fresh clone

**Comment by hepcat72** [comment]
You know, I tried linting new files that are `git add`ed, but apparently that doesn't get linted either.  Apparently it only lints committed files? Maybe I made a mistake.  I'll try the pre-commit hook and see if that works, but if I did it correctly in my manual testing, then I don't think pre-commit will work.

**Comment by ferrarimarco** [comment]
Hi @hepcat72 ! This is currently not supported.

What is supported is:

- Run against the whole codebase (set `VALIDATE_ALL_CODEBASE` to `true`).
- Run against the files that changed in the last commit (`VALIDATE_ALL_CODEBASE` to `false`, the default).

To partially cover your use case, you would need to set `VALIDATE_ALL_CODEBASE` to `true`, and `USE_FIND_ALGORITHM` to `true`. This will lint all the files in your workspace, including the newly `git add`ed files.

I'll be happy to review a PR to implement this.

**Comment by ferrarimarco** [comment]
PS: to run super-linter locally, you can refer to https://github.com/super-linter/super-linter/blob/main/docs/run-linter-locally.md

**Comment by ferrarimarco** [comment]
Yes, it will work :)

**Comment by hepcat72** [comment]
Before I start playing with this, let me ask straight-up... if I use `USE_FIND_ALGORITHM=true` (with either the regex or all files), would that actually work on untracked files or only files that have been `git add`ed?  (I'm not sure that my assumption that it can only check `git add`ed files is correct.)

**Comment by ferrarimarco** [comment]
When you set `USE_FIND_ALGORITHM=true`, you're telling super-linter to completely bypass Git to gather the list of files to lint, and use `find` instead. In this mode, `VALIDATE_ALL_CODEBASE` is assumed to be `true` because there is no way to make assumptions about changed files using `find` only.

So, to answer your question: `USE_FIND_ALGORITHM=true` will make super-linter get both tracked and untracked files.
