### ISSUE TITLE
Slim image for specific linters

### ISSUE THREAD

**Issue by JobaDiniz** [super-linter/super-linter#4797]
Is it possible to select which *language linters* are pulled instead of choosing between `slim` vs `whole` images?
As an example, my project only has `markdown` and `c#` files, and I didn't want to pull the whole image, but the *slim* image does not have `c#`.

**Comment by zkoppert** [comment]
It is not possible to be able to do this in a configurable way right now. You would need to fork the super0linter project and then only put in the linters you wanted.

**Comment by echoix** [comment]
@JobaDiniz That's more of a MegaLinter thing, having specific flavors to handle more effectively projects using only certain linters.
For example, there is 
https://megalinter.io/latest/flavors/dotnet/
And
https://megalinter.io/latest/flavors/dotnetweb/


All the flavors are listed here
https://megalinter.io/latest/flavors/ and when running an image, where another smaller flavor would suit the files in your project, MegaLinter will suggest you to use another flavor. 


You can take a look here
https://megalinter.io/latest/
