### ISSUE TITLE
.mypy_cache written back to filesystem as root:root

### ISSUE THREAD

**Issue by kftsehk** [super-linter/super-linter#4822]
## Describe the bug

An issue with docker mount volume would write as `root`, that might lead to unexpected result, e.g. unable to remove files

## Expected behavior

In my opinion, super-linter should not write anything back to host, except if e.g. user explicitly request a log file to be written (if such feature exists)

## Steps to Reproduce

```
docker run \
  -e RUN_LOCAL=true \
  -e VALIDATE_PYTHON_MYPY=true\
  -e VALIDATE_ALL_CODEBASE=true \
  -v $(pwd):/tmp/lint \
  ghcr.io/super-linter/super-linter:slim-latest
```

A folder `.mypy_cache` is written and since it is written from container, ownership likely `root:root`

## Additional context

I am not sure if `-v $(pwd):/tmp/lint:ro` would break something.

Retaining cache might be useful for future re-use of linter, but with the current permission issue, does not seem to be implemented correctly. 

E.g. user have no permission to update `.mypy_cache` if mypy is used both inside the container and by the user.

**Comment by ferrarimarco** [comment]
I think there are a few more leftovers that we should clean up:

- `.lintr`: I think we create this one in some cases. We should delete it only if we created it.
- `logback.log`: this one might come from one of the Java linters.

**Comment by ferrarimarco** [comment]
@kftsehk: Where is the `.mypy_cache` directory created?

**Comment by ferrarimarco** [comment]
Given that we enable the `--install-types` option, we cannot disable the cache. We either need to delete it after each run, or configure a non-root user in the container.

**Comment by alexanderbazhenoff** [comment]
The same problem: this folder created inside of `${CI_PROJECT_DIR}`, default build directory at GitLab CI runner. Is any variable or flag to solve this, except `VALIDATE_PYTHON_MYPY=false` or giving access to `sudo rm` command for `gitlab-runner` user without a password in `sudoers` file? This is not a good idea to give this user sudo privileges at all. Currently disabled mypy, but hope you'll find a solution.

**Comment by ferrarimarco** [comment]
I suppose we can start by cleaning it up after each run, as we do with other artifacts.

> The same problem: this folder created inside of `${CI_PROJECT_DIR}`, [default build directory at GitLab CI runner](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html). Is any variable or flag to solve this, except `VALIDATE_PYTHON_MYPY=false` or giving access to `sudo rm` command for `gitlab-runner` user without a password in `sudoers` file? This is not a good idea to give this user sudo privileges at all. Currently disabled mypy, but hope you'll find a solution.

So, after a super-linter run, you find a `.mypy_cache` directory at in the directory containing the root of your repository, right?

**Comment by ferrarimarco** [comment]
#5210 should take care of this.

**Comment by alexanderbazhenoff** [comment]
> So, after a super-linter run, you find a `.mypy_cache` directory at in the directory containing the root of your repository, right?

Yeah, created on the first run and unable to remove on the second run. All used gitlab-runner settings are 'out from the box'.
