### ISSUE TITLE
Hadolint catching non dockerfiles

### ISSUE THREAD

**Issue by Chocrates** [super-linter/super-linter#4846]
## Describe the bug

I have a file in my repository with a name like "01-dockerfile.md" that has some documentation on using Docker with the repo.  Unfortunately hadolint is picking that file up and trying to lint it as a Dockerfile, causing errors.

I believe this regex is the culprit https://github.com/super-linter/super-linter/blob/main/lib/functions/buildFileList.sh#L431

It seems that we could change the regex to just check for:
- `dockerfile`
- `containerfile`
- `*.dockerfile`
- `*.containerfile`

I am not a container expert though so unsure if doing something like that would break other uses.  

## Expected behavior

Only pick up container files

## Steps to Reproduce

1. Add a text file to your repository with `dockerfile` in the filename.
1. Run the linter
1. Get the results and notice the bug!

**Comment by zkoppert** [comment]
@Chocrates Thanks for finding this one and opening an issue! Based on the [docs for Docker](https://docs.docker.com/build/building/packaging/#filename) it looks like `Dockerfile` and `something.Dockerfile` are the recommended file naming conventions so I think its ok to limit to that.

**Comment by Chocrates** [comment]
Sounds good @zkoppert.  I'll also include `Containerfile` and `*.containerfile` based on https://github.com/super-linter/super-linter/pull/1987

I'll try to get a PR today for that.

**Comment by zkoppert** [comment]
Thank you!!
