### ISSUE TITLE
Bump Spectral Version

### ISSUE THREAD

**Issue by dev-bio** [super-linter/super-linter#4892]
Please bump `@stoplight/spectral` to version 6.9.0 as the current one has a transitive dependency on `vm2` (discontinued), which has a critical sandbox breakout vulnerability.

**Comment by ferrarimarco** [comment]
We have that dependency managed by DependaBot. Let me check what's going on.

**Comment by ferrarimarco** [comment]
The dependency ID changed from `@stoplight/spectral` to `@stoplight/spectral-cli`. That's why Dependabot is not suggesting updates anymore.
