### ISSUE TITLE
Move the only wiki page about adding new languages to docs

### ISSUE THREAD

**Issue by ferrarimarco** [super-linter/super-linter#4949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There's only one page in the wiki: https://github.com/super-linter/super-linter/wiki/Adding-new-language-support-to-Super-Linter.

### Expected Behavior

I think we should:

- Move it to the `docs` directory for consistency.
- Disable the wiki so we have less things to maintain.

**Comment by zkoppert** [comment]
Sounds great. I'm not a big fan of wikis.
