### ISSUE TITLE
Git repository validation should not be enforced when USE_FIND_ALGORITHM=true

### ISSUE THREAD

**Issue by rmatte** [super-linter/super-linter#4952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PR #4889 (Exit on errors when running Git) was merged 2 days ago.

This code was added to lib/functions/validation.sh:

```
function ValidateLocalGitRepository() {
  debug "Check if ${GITHUB_WORKSPACE} is a Git repository"
  if ! git -C "${GITHUB_WORKSPACE}" rev-parse --git-dir; then
    fatal "${GITHUB_WORKSPACE} is not a Git repository."
  else
    debug "${GITHUB_WORKSPACE} is a Git repository"
  fi

  debug "Git branches: $(git -C "${GITHUB_WORKSPACE}" branch -a)"
}
```

Because that exits as fatal if the directory being linted isn't a git repo it completely breaks the ability to lint any directories which are not git repos.

### Expected Behavior

We've been using super-linter to lint directories which aren't git repos for quite a while now and this change broke that for us. This is a great linter and in my opinion it should work whether or not the directory is a git repo.

### Super-Linter version

```markdown
latest
```

### Relevant log output

```shell
[FATAL]   /tmp/lint is not a Git repository.
```

### Steps To Reproduce

1. Run super-linter against a directory that isn't a git repo.
2. Observe that it fails with the error "[FATAL]   /tmp/lint is not a Git repository."
3. Try the same with a previous version from before that PR, such as v5.7.1
4. Observe that it works fine with 5.7.1 and we're able to lint the contents of the directory.

**Comment by rmatte** [comment]
I found something interesting while looking in to this. It seems that the intention is to allow us to skip over that validation if USE_FIND_ALGORITHM=true but in the lib/linter.sh file it has...

```
if [[ "${USE_FIND_ALGORITHM}" != "false" ]] || [[ "${VALIDATE_ALL_CODEBASE}" != "true" ]]; then
  debug "Validate the local Git environment"
  ValidateLocalGitRepository
  ValidateGitShaReference
  ValidateDefaultGitBranch
else
  debug "Skipped the validation of the local Git environment because we don't depend on it."
fi
```

USE_FIND_ALGORITHM=true is supposed to use the Linux "find" command instead of "git diff" so I'm fairly certain that what they intended for that if statement is actually...

```
if [[ "${USE_FIND_ALGORITHM}" != "true" ]] || [[ "${VALIDATE_ALL_CODEBASE}" != "true" ]]; then
```

That way we could just enable USE_FIND_ALGORITHM to tell it to use find instead of git and work around this issue.

**Comment by ferrarimarco** [comment]
Hi @rmatte !

In your report, you stated that this happens on `v5.7.2`. Is that so? The PR you mentioned landed in the `latest`, so it `v5.7.2` should work. Can you confirm this?

**Comment by rmatte** [comment]
> Hi @rmatte !
> 
> In your report, you stated that this happens on `v5.7.2`. Is that so? The PR you mentioned landed in the `latest`, so it `v5.7.2` should work. Can you confirm this?

Sorry, I was probably just confusing them, we are seeing this problem on latest. I just thought latest was v5.7.2 but apparently I was mistaken, my bad.

**Comment by ferrarimarco** [comment]
(and thanks for triaging this issue!)

**Comment by rmatte** [comment]
> (and thanks for triaging this issue!)

Did you need me to submit a PR to correct the issue that I detailed in my comment above or will you be taking care of that on your end? Thanks :)

**Comment by ferrarimarco** [comment]
I just submitted #4953. It's still a draft because I'd like to have a failing workflow first, so we can fix it.

This helps avoiding this issue in the future :)

**Comment by rmatte** [comment]
> I just submitted #4953. It's still a draft because I'd like to have a failing workflow first, so we can fix it.
> 
> This helps avoid this issue in the future :)

When I look at the commit for that it only appears to include the code for "2. Add a workflow step to catch this issue."

**Comment by kftsehk** [comment]
fyi last good is docker image `super-linter/super-linter:slim-v5.7.2` or `super-linter/super-linter:v5.7.2` in case you need to get a round while fixing

**Comment by rmatte** [comment]
I can confirm that the latest release resolves this when USE_FIND_ALGORITHM=true is in use. Thanks for all your work on this @ferrarimarco.
