### ISSUE TITLE
Implement more test cases

### ISSUE THREAD

**Issue by kftsehk** [super-linter/super-linter#4954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Command:
```
# no issue when USE_FIND_ALGORITHM=false
docker run --rm \
    -e RUN_LOCAL=true \
    -e USE_FIND_ALGORITHM=true \
    -v "$(git rev-parse --show-toplevel)":/tmp/lint ghcr.io/super-linter/super-linter:slim-latest
```

Error
```
...
[DEBUG] Validate the local Git environment
[DEBUG] Check if /tmp/lint is a Git repository
.git
[DEBUG] /tmp/lint is a Git repository
[DEBUG] Git branches: 
* main
  dev
[DEBUG] Validate that the GITHUB_SHA reference () exists in this Git repository.
[FATAL] The GITHUB_SHA reference () doesn't exist in this Git repository
```

5a8805dc4fb3ff22315a0c7f8ce8d3cc7da81958 is the first bad commit

### Expected Behavior

up to v5.7.2
Super-linter shall run till the end and report the result for both `USE_FIND_ALGORITHM=true` and `USE_FIND_ALGORITHM=false`

### Super-Linter version

```markdown
slim-latest
```

### Relevant log output

```shell
Digest of git bisect log


grep -i -E -e '(BUILD_REVISION|naming to|fatal)' bisect.log 
        --build-arg BUILD_REVISION=2ac4d451 \
#113 naming to ghcr.io/super-linter/super-linter:latest 0.0s done
fatal: Not a valid object name 
2023-12-06 06:10:27 [FATAL]   The GITHUB_SHA reference () doesn't exist in this Git repository
        --build-arg BUILD_REVISION=4645b766 \
#113 naming to ghcr.io/super-linter/super-linter:latest 0.0s done
fatal: Not a valid object name 
2023-12-06 06:12:48 [FATAL]   The GITHUB_SHA reference () doesn't exist in this Git repository
        --build-arg BUILD_REVISION=879672e9 \
#113 naming to ghcr.io/super-linter/super-linter:latest 0.0s done
fatal: Not a valid object name 
2023-12-06 06:14:35 [FATAL]   The GITHUB_SHA reference () doesn't exist in this Git repository
        --build-arg BUILD_REVISION=5a8805dc \
#113 naming to ghcr.io/super-linter/super-linter:latest 0.0s done
fatal: Not a valid object name 
2023-12-06 06:16:46 [FATAL]   The GITHUB_SHA reference () doesn't exist in this Git repository
5a8805dc4fb3ff22315a0c7f8ce8d3cc7da81958 is the first bad commit
```

### Steps To Reproduce

```
docker run --rm \
    -e RUN_LOCAL=true \
    -e USE_FIND_ALGORITHM=true \
    -v "$(git rev-parse --show-toplevel)":/tmp/lint ghcr.io/super-linter/super-linter:slim-latest
```

### Anything else?

The error message above is from here

https://github.com/super-linter/super-linter/blob/5a8805dc4fb3ff22315a0c7f8ce8d3cc7da81958/lib/functions/validation.sh#L237-L244

I assume this is for checking `GITHUB_SHA` provided by github-action against the checked out commit

In local run I have not seen documentation or reason why this variable has to be set, I guess user are more likely commanding `RUN_LOCAL=true` to
> lint my directory here as is, regardless it has git or not, it is dirty or not, or which reference, branch or tag I am at

supported by #4952 that a local run is used to lint a non-git directory.

I have not enough understanding on the commit 5a8805dc4fb3ff22315a0c7f8ce8d3cc7da81958 to move the issue forward or digging deeper down.

**Suggestion**

The only suggestion I would make is, as `RUN_LOCAL=true` is a supported and an important feature to guard non-conforming code from being pushed to remote, CI/CD should make better coverage on various global flags, and also the case of non-git directory.

| **ENV VAR**                   | **Default Value** | **Test Coverage and Requirement**  | **Notes**                                                                                                                                                                        |
| ----------------------------- | ----------------- | ---------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **ERROR_ON_MISSING_EXEC_BIT** | `false`           | `true` covered, is sufficient      | If set to `false`, the `bash-exec` linter will report a warning if a shell script is not executable. If set to `true`, the `bash-exec` linter will report an error instead.      |
| **USE_FIND_ALGORITHM**        | `false`           | `true` not covered, both required  | By default, we use `git diff` to find all files in the workspace and what has been updated, this would enable the Linux `find` method instead to find all files to lint          |
| **EXPERIMENTAL_BATCH_WORKER** | `false`           | `true` not covered, both required  | Flag to enable experimental parallel and batched worker. As of current only `eslint` and `cfn-lint` are supported, if there is no support, original version is used as fallback  |
| **IGNORE_GENERATED_FILES**    | `false`           | `true` not covered, both required  | If set to `true`, super-linter will ignore all the files with `@generated` marker but without `@not-generated` marker.                                                           |
| **IGNORE_GITIGNORED_FILES**   | `false`           | `true` not covered, both required  | If set to `true`, super-linter will ignore all the files that are ignored by Git.                                                                                                |
| **VALIDATE_ALL_CODEBASE**     | `true`            | `false` not covered, both required | Will parse the entire repository and find all files to validate across all types. **NOTE:** When set to `false`, only **new** or **edited** files will be parsed for validation. |
| **[non-env] Input directory is a git directory** |  no default                 | `false` not covered, both required | User might lint a git tracked directory, or a plain directory without version control, for some reason                                                                           |

**Comment by ferrarimarco** [comment]
Hi, and thanks for this detailed report.

This issue, and running super-linter with `USE_FIND_ALGORITHM=true` is going to be fixed in #4953, so this may be considered a duplicate, but let's keep it open as a request to track the other cases you listed in the `suggestions` section.

Thanks!
