### ISSUE TITLE
JSON linting still very slow on medium size files

### ISSUE THREAD

**Issue by rtk-willm** [super-linter/super-linter#5073]
### Is there an existing issue for this?

- [X] I have searched the existing issues. Similar issue https://github.com/super-linter/super-linter/issues/2713 and made comment https://github.com/super-linter/super-linter/issues/2713#issuecomment-1870653818

### Current Behavior

I have approximaely 300 mb+ of json files linting in my code base with the biggest files being about 150kb so not huge. This is taking several hours to lint on standard Github runners. A little slow but several hours seems the wrong order of magnitude for JSON linting which should be fairly processor light process.

When debugging is enabled I can see lots of other  linters are running despite only having json linting enabled.

### Expected Behavior

* Settings show can either enable the linters you want to run or disable the ones you don't. When enabling just JSON linting the expectation would be that only that is run, the majority of use cases of JSON linting do not need to check whether correctly validated as ARM file for example.
* Takes a few minutes to run

### Super-Linter version

```markdown
v5.7.2 which as of writing is the latest version
```

### Relevant log output

```shell
....

2023-12-27 21:56:33 [DEBUG]   File:[/path/subpath/xxx.json], File_type:[json], Base_file:[xxx.json]
2023-12-27 21:56:33 [DEBUG]   Checking if /path/subpath/xxx.json is an OpenAPI file...
2023-12-27 21:56:33 [DEBUG]   /path/subpath/xxx.json is NOT an OpenAPI descriptor
2023-12-27 21:56:33 [DEBUG]   Checking if /path/subpath/xxx.json is an ARM file...
2023-12-27 21:56:33 [DEBUG]   Checking if /path/subpath/xxx.json is a Cloud Formation file...
2023-12-27 21:56:33 [DEBUG]   Checking if /path/subpath/xxx.json is a AWS states descriptor...

...
```

### Steps To Reproduce

Github Workflow Config

```
      - name: Lint Code Base
        id: super
        uses: super-linter/super-linter/slim@v5.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true 
          VALIDATE_JSON: true
          FILTER_REGEX_INCLUDE: (./some_location\/.*)
          ACTIONS_RUNNER_DEBUG: true
```

**Comment by ferrarimarco** [comment]
Hi @rtk-willm !

Let's try to troubleshoot this issue.

To understand what's happening, we need a few more logs. What I would like to understand is how much time it takes to scan files and to actually lint them.

I'm interested in the timestamps of:

- The first log message
- The `--- ENV (before running linters) ---` message
- The `The script has completed` message

**Comment by ferrarimarco** [comment]
Also:

> Settings show can either enable the linters you want to run or disable the ones you don't. When enabling just JSON linting the expectation would be that only that is run, the majority of use cases of JSON linting do not need to check whether correctly validated as ARM file for example.

This is already implemented and working as expected, as explained at the bottom of [this README section](https://github.com/super-linter/super-linter?tab=readme-ov-file#configure-super-linter).

What it's not there yet is to avoid potentially expensive I/O operations to get the type of a file if we're not going to lint it anyway. #5094 addresses this particular aspects, but without the data points I pointed out in [my previous comment](https://github.com/super-linter/super-linter/issues/5073#issuecomment-1871850613) we don't know how much impact it will have on your particular case.

**Comment by rtk-willm** [comment]
Sorry about slow reply, I couldn't get it to complete on Github runners due to six hour timeout, so couldn't get the information you requested. I spent time configuring to run locally and with the below command 
```
docker run --rm     -e VALIDATE_ALL_CODEBASE=true -e VALIDATE_JSON=true -e FILTER_REGEX_INCLUDE='(./deployments\/f.*)' -e ACTIONS_RUNNER_DEBUG=true -e RUN_LOCAL=true  -w /tmp/lint   -v "$(git rev-parse --show-toplevel)":/tmp/lint github/super-linter:slim-latest > lint_results 2>&1
```

I got:
The first log message
```
[0m2024-01-03 18:42:03 ^[[0;34m[DEBUG]^[[0m   Setting FILE_ARRAY_ANSIBLE variable...^[[0m
```
The --- ENV (before running linters) --- message
```
[0m2024-01-03 19:06:37 ^[[0;34m[DEBUG]^[[0m   --- ENV (before running linters) ---^[[0
```
The script has completed message
```
^[[0m2024-01-03 19:55:50 ^[[0;34m[INFO]^[[0m   The script has completed^[[0m
```

Whereas if I run this Eslint directly, it is multiple magnitudes faster
```
time eslint 'deployments/f*.json'

xxx5.json
  13:2  error  Duplicate object key  json/*
  14:2  error  Duplicate object key  json/*
  15:2  error  Duplicate object key  json/*
  16:2  error  Duplicate object key  json/*

✖ 4 problems (4 errors, 0 warnings)

eslint 'deployments/f*.json'  2.96s user 0.32s system 133% cpu 2.469 total
```

**Comment by ferrarimarco** [comment]
Thanks for these details, these data points are really helpful.

It took about:

- 23 mins to scan for files: #5094 should mitigate this.
- 49 mins to lint those files with eslint: I think this is the same as #5043

**Comment by ferrarimarco** [comment]
If you feel adventurous, you test if #5094 has any effect by doing the following:

1. Clone the super-linter repository:

    ```shell
    git clone https://github.com/super-linter/super-linter.git
    cd super-linter
    git checkout update-detect
    ```

2. Build the super-linter container image (it should take 15ish mins):

    ```shell
    make docker
    ```

3. Run super-linter against your code base:

```shell
docker run --rm \
  -e VALIDATE_ALL_CODEBASE=true \
  -e VALIDATE_JSON=true \
  -e FILTER_REGEX_INCLUDE='(./deployments\/f.*)' \
  -e ACTIONS_RUNNER_DEBUG=true \
  -e RUN_LOCAL=true  \
  -w /tmp/lint   \
  -v "$(git rev-parse --show-toplevel)":/tmp/lint \
  ghcr.io/super-linter/super-linter:latest > lint_results 2>&1
```

PS: In your log, what is the version that super-linter reports at the beginning of the log? I expect it to be an old version because the Docker Registry image is not being pushed anymore.

**Comment by ferrarimarco** [comment]
PPS: here are the complete instructions to run super-linter locally: https://github.com/super-linter/super-linter?tab=readme-ov-file#run-super-linter-outside-github-actions

**Comment by rtk-willm** [comment]
Hi 
Here are new results with locally built Docker file

```
[0m2024-01-04 18:28:05 ESC[0;34m[DEBUG]ESC[0m   Setting FILE_ARRAY_ANSIBLE variable...ESC[0m
...
[0m2024-01-04 18:43:46 ESC[0;34m[DEBUG]ESC[0m   --- ENV (before running linters) ---ESC[0m
...
19:22:46 ESC[0;34m[INFO]ESC[0m   The script has completedESC
```
So quite a bit faster. Interestingly though if you have a deep look at the logs you can see with `super-linter` that each files is being linted in the range 1-2s
```
ESC[0m2024-01-04 18:43:46 ESC[0;34m[DEBUG]ESC[0m   Linting FILE: /tmp/lint/deployments/xxxx.jsonESC[0m
ESC[0m2024-01-04 18:43:46 ESC[0;34m[DEBUG]ESC[0m   FILE_STATUS (xxxx.json) is empty, or not set to 'good' or 'bad'. Assuming it should be linted correctly. Setting FILE_STATUS to 'good'...ESC[0m
ESC[0m2024-01-04 18:43:46 ESC[0;34m[DEBUG]ESC[0m   File: /tmp/lint/deployments/xxxx.json, FILE_NAME: xxxx.json, DIR_NAME:/tmp/lint/deployments, FILE_STATUS: good, INDIVIDUAL_TEST_FOLDER: json, TEST_CASE_DIRECTORY: test/linters/jsonESC[0m
ESC[0m2024-01-04 18:43:46 ESC[0;34m[DEBUG]ESC[0m   Updated TEST_CASE_DIRECTORY for JSON to: test/linters/json/ESC[0m
ESC[0m2024-01-04 18:43:46 ESC[0;34m[INFO]ESC[0m   ---------------------------ESC[0m
ESC[0m2024-01-04 18:43:46 ESC[0;34m[INFO]ESC[0m   File:[/tmp/lint/deployments/xxxx.json]ESC[0m
ESC[0m2024-01-04 18:43:48 ESC[0;34m[INFO]ESC[0m    - File:ESC[0;37m[xxxx.json]ESC[0;34m was linted with ESC[0;37m[eslint]ESC[0;34m successfullyESC[0m
ESC[0m2024-01-04 18:43:48 ESC[0;34m[DEBUG]ESC[0m   Error code: 0. Command output:ESC[0m
```

Whereas after enabling more debugging information in ESlint this appears to be in ms range

```
2024-01-04T20:14:28.628Z eslint:file-enumerator Yield: xxxxx.json
2024-01-04T20:14:28.628Z eslintrc:cascading-config-array-factory Load config files for xxxxxxxx.
2024-01-04T20:14:28.628Z eslintrc:cascading-config-array-factory Cache hit: xxxxxxxx.
2024-01-04T20:14:28.628Z eslint:cli-engine Lint xxxxxxxx/xxxxx.json
2024-01-04T20:14:28.628Z eslint:linter Linting code for xxxxxxxx/xxxxx.json (pass 1)
2024-01-04T20:14:28.629Z eslint:linter Verify
2024-01-04T20:14:28.629Z eslint:linter With ConfigArray: xxxxxxxx/xxxxx.json
2024-01-04T20:14:28.629Z eslint:linter Apply the processor: 'json/.json'
2024-01-04T20:14:28.631Z eslint:linter A code block was found: '(unnamed)'
2024-01-04T20:14:28.633Z eslint:linter Parsing: xxxxxxxx/xxxxx.json
2024-01-04T20:14:28.634Z eslint:linter Parsing successful: xxxxxxxx/xxxxx.json
2024-01-04T20:14:28.634Z eslint:linter Scope analysis: xxxxxxxx/xxxxx.json
2024-01-04T20:14:28.635Z eslint:linter Scope analysis successful: xxxxxxxx/xxxxx.json
2024-01-04T20:14:28.640Z eslint:linter Generating fixed text for xxxxxxxx/xxxxx.json (pass 1)
2024-01-04T20:14:28.640Z eslint:source-code-fixer Applying fixes
2024-01-04T20:14:28.640Z eslint:source-code-fixer shouldFix parameter was false, not attempting fixes
2024-01-04T20:14:28.640Z eslintrc:ignore-pattern Check {
  filePath: 'xxxxxxxx/xxxxxxx.json',
  dot: false,
  relativePath: 'deployments/xxxxxxx.json',
  result: false
}
```

**Comment by ferrarimarco** [comment]
Thanks for the additional data points! They are quite useful.

At least that PR had some effect on the file scan (23 mins vs 15 mins), but it's way too much. Is there a chance you can share the log, so that I can have a look at why it's taking this long for the file scan?

For the linting step, I think we're paying the performance tax to start eslint once per file.

We need to fix both issues.

**Comment by rtk-willm** [comment]
hey no problem. Happy to answer questions about logs but I can't share entire logs as likely have sensitive data in them.

**Comment by ferrarimarco** [comment]
That's what I imagined :)

I'll see if I can generate some JSON files to reproduce the issue.

Does super-linter report any validation errors? I suppose that this doesn't influence the total run time.

**Comment by rtk-willm** [comment]
sorry 😄 , I did have a look at generating random JSON myself with something like https://github.com/Ankur-Jat/random-json-generator/tree/master but haven't had time yet

**Comment by ferrarimarco** [comment]
Well, I went the simple route I guess :)

```shell
for i in {1..2000}; do
  {
    printf '{"random_numbers": ['
    shuf -i 1-10000000 | head -c 149500 | tr '\n' ','
    printf '1]}\n'
  } > "file_$i.json"
done
```

**Comment by rtk-willm** [comment]
nice, how did that go? There must be some start costs of running the linters individually I expect. As to your question before about errors (sorry I missed it), there were a couple of errors out of about 70k files. They didn't seem to have any effect on speed of running `eslint` directly though :)

**Comment by ferrarimarco** [comment]
With 2000 JSON files, the file listing step completes in under a minute after the optimizations in #5094, so I suppose that's beneficial.

ESlint invocations take a lot of time, file by file so that's an area to improve. I'll think about how to solve this. :)

**Comment by rtk-willm** [comment]
okay thankyou

**Comment by ferrarimarco** [comment]
Status update: I've sent a few preliminary PRs to pave the way for a scalable and maintainable solution to this issue.

**Comment by rtk-willm** [comment]
brilliant, thanks very much 🙏

**Comment by ferrarimarco** [comment]
@kftsehk I think is a case for implementing batched (and eventually parallel) support. I'll recover your work in a draft PR so we can collaborate on that one. Thanks for putting it together!

**Comment by ferrarimarco** [comment]
Quick update: we are almost done with the preparatory PRs!

**Comment by ferrarimarco** [comment]
We finally have a PR to (hopefully) fix this, and make the whole process way quicker! #5177

**Comment by rtk-willm** [comment]
brilliant, thanks for all your hard work @ferrarimarco 🙏

**Comment by ferrarimarco** [comment]
👍 

You can try the changes if you want: follow the steps in https://github.com/super-linter/super-linter/issues/5073#issuecomment-1876713819, but checkout the `parallel-batched` branch instead of the `update-detect` one. Thanks!

**Comment by rtk-willm** [comment]
hey, thanks for the tip. I tried it a few times but unfortunately for some reason the `perl` install and build section keeps failing for me and haven't worked with `perl` much myself

```
Dockerfile:171
--------------------
 170 |     ##############################
 171 | >>> RUN apk add --no-cache --virtual .perl-build-deps \
 172 | >>>     gcc \
 173 | >>>     make \
 174 | >>>     musl-dev \
 175 | >>>     perl-dev \
 176 | >>>     && curl --retry 5 --retry-delay 5 -sL https://cpanmin.us/ \
 177 | >>>     | perl - -nq --no-wget \
 178 | >>>     Perl::Critic \
 179 | >>>     Perl::Critic::Bangs \
 180 | >>>     Perl::Critic::Community \
 181 | >>>     Perl::Critic::Lax \
 182 | >>>     Perl::Critic::More \
 183 | >>>     Perl::Critic::StricterSubs \
 184 | >>>     Perl::Critic::Swift \
 185 | >>>     Perl::Critic::Tics \
 186 | >>>     && apk del --no-network --purge .perl-build-deps
 187 |
--------------------
ERROR: failed to solve: process "/bin/bash -o errexit -o nounset -o pipefail -c apk add --no-cache --virtual .perl-build-deps     gcc     make     musl-dev     perl-dev     && curl --retry 5 --retry-delay 5 -sL https://cpanmin.us/     | perl - -nq --no-wget     Perl::Critic     Perl::Critic::Bangs     Perl::Critic::Community     Perl::Critic::Lax     Perl::Critic::More     Perl::Critic::StricterSubs     Perl::Critic::Swift     Perl::Critic::Tics     && apk del --no-network --purge .perl-build-deps" did not complete successfully: exit code: 60
make: *** [docker] Error 1
```

**Comment by ferrarimarco** [comment]
Ah! Thanks for trying. I don't see that error when building the image. Hopefully it's transient. Let's see...

**Comment by rtk-willm** [comment]
hmm not sure, have tried several times. I am on a non M1 mac if that context helps at all 🤷‍♂️
