### ISSUE TITLE
How to lint only the changed files?

### ISSUE THREAD

**Issue by acbin** [super-linter/super-linter#5075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My code repository contains a large number of files, and formatting the entire codebase every time would take several hours. How can I configure it to achieve the effect of "formatting only the changed files"?

### Expected Behavior

formatting only the changed files

**Comment by AndreyMlashkin** [comment]
So, what's the plan about it? You're not going to include it to the roadmap? why?

**Comment by ferrarimarco** [comment]
Hi @AndreyMlashkin and @acbin 

This is already implemented. See the `VALIDATE_ALL_CODEBASE` configuration variable.
