### ISSUE TITLE
Manage or deprecate Docker Hub images

### ISSUE THREAD

**Issue by ferrarimarco** [super-linter/super-linter#5095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are a few container images on Docker Hub under the `github` namespace: https://hub.docker.com/r/github/super-linter

We are not pushing new images to `github/super-linter` since `v5.0.0`.

### Expected Behavior

Deprecate https://hub.docker.com/r/github/super-linter or start pushing images there again. Given that we already have infrastructure in place to push to GitHub Container Registry, we shall probably deprecate it to reduce the amount of things to maintain, unless we have a specific reason for keeping it.

### Anything else?

@zkoppert I don't have the credentials to manage https://hub.docker.com/r/github/super-linter, do you?

Thanks!

**Comment by ferrarimarco** [comment]
@zkoppert ping :)

**Comment by zkoppert** [comment]
I don't have the credentials to manage that. I've asked around but haven't gotten any results. :(

**Comment by ferrarimarco** [comment]
Thanks for checking. Maybe @admiralAwkbar knows? :)

Or, is there an escalation path for the [`github` community organization on Docker Hub](https://hub.docker.com/u/github)?

**Comment by ferrarimarco** [comment]
Closing this because of lack of a path forward :(
