### ISSUE TITLE
Readme Options List a Bit Long

### ISSUE THREAD

**Issue by noremacskich** [super-linter/super-linter#5154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As of right now, the readme has 130+ options on it, sorted alphabetically.

### Expected Behavior

I would expect the options to be grouped together a bit more reasonably, I would say by linter type, and a separate section for overall config options.

Something to this effect

![image](https://github.com/super-linter/super-linter/assets/1461956/2b53acde-8ab6-4ef9-8eb2-36a48602358f)

### Anything else?

I have some free time, and can get that thrown together, though might need some help with options that are not immediately obvious to where they should go.

I was wanting to make sure people were okay with that, before diving into converting the whole thing

**Comment by ferrarimarco** [comment]
Hi @noremacskich ! I think it makes sense, the table is quite long.

Perhaps grouping by linter would make the readme too crowded tho? Most linters have only 2 variables (flag to enable/disable, rules file name). I guess we can start by grouping the `VALIDATE_xxx` into one table, and the rest in another one? WDYT?

Thanks for this proposal, we'll be happy to review a PR.
