### ISSUE TITLE
Outdated pylint config value for overgeneral-exceptions

### ISSUE THREAD

**Issue by rmatte** [super-linter/super-linter#5220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
2024-02-02 21:53:28 [INFO]   Command output for PYTHON_PYLINT:
------
pylint: Command line or configuration file:1: UserWarning: 'Exception' is not a proper value for the 'overgeneral-exceptions' option. Use fully qualified name (maybe 'builtins.Exception' ?) instead. This will cease to be checked at runtime when the configuration upgrader is released.
------
```

Getting the above error, this seems to be because of this config file entry in the docker image...

/action/lib/.automation/.python-lint: overgeneral-exceptions=Exception

It wants that to be defined as builtins.Exception instead. That will need to be corrected, otherwise pylint will error out like this each time it runs via the docker image.

### Expected Behavior

Should work without erroring.

### Super-Linter version

```markdown
I can't figure out how to get the version from inside the container and it doesn't seem to output
it when running. It's either 6.0.0 or 5.7.2. I pulled it down yesterday (02/01/2024) as the latest
docker image, so whatever version that would be.
```

### Relevant log output

```shell
2024-02-02 21:53:28 [INFO]   Command output for PYTHON_PYLINT:
------
pylint: Command line or configuration file:1: UserWarning: 'Exception' is not a proper value for the 'overgeneral-exceptions' option. Use fully qualified name (maybe 'builtins.Exception' ?) instead. This will cease to be checked at runtime when the configuration upgrader is released.
------
```

### Steps To Reproduce

Run the latest version of super-linter against some python code.

**Comment by ferrarimarco** [comment]
This is likely right: https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#overgeneral-exceptions

```
Default: ('builtins.BaseException', 'builtins.Exception')
```

Feel free to send a PR to fix this, I'll happily review it.

File to edit: https://github.com/super-linter/super-linter/blob/main/TEMPLATES/.python-lint

Thanks!

**Comment by ferrarimarco** [comment]
#5252 should take care of this
