### ISSUE TITLE
Lint XSD files

### ISSUE THREAD

**Issue by Dosanyintolu1** [super-linter/super-linter#5248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use the `VALIDATE_XML`, I always get a successful build even with multiple errors in the file.

### Expected Behavior

I expect error outputs when malformed xsd files are linted.

### Super-Linter version

```markdown
v6.0.0
```

### Relevant log output

```shell
none
```

### Steps To Reproduce

1. Include the following in the xsd file:
```
<?xml version = "1.0" encoding = "UTF-8"?>
<!-- $Header: /cvsroot/ebxmlrr/ebxmlrr-spec/misc/3.0/schema/rim.xsd,v 1.20 2005/02/03 19:28:15 farrukh_najmi Exp $ -->
<schema targetNamespace="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" 
  xmlns="http://www.w3.org/2001/XMLSchema" 
  xmlns:tns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0"
  xmlns:xml="http://www.w3.org/XML/1998/names=
      <maxLength value="4"/>
```
2. Push to github and run the action.
3. Below is my output with the above xml in my xsd file.
![Screenshot 2024-02-08 at 5 48 26 PM](https://github.com/super-linter/super-linter/assets/127335828/230ece9e-c28d-4015-a72e-017284110350)

**Comment by ferrarimarco** [comment]
Hi @Dosanyintolu1 !

`Include the following in the xsd file`: what extension does the file have?

In the current implementation, super-linter lints files with a `.xml` extension using [xmllint](https://gnome.pages.gitlab.gnome.org/libxml2/xmllint.html). We can probably check `.xsd` files as well. `xmllint` seems to support this, at least for syntax.

**Comment by ferrarimarco** [comment]
#5250 should take care of this

**Comment by Dosanyintolu1** [comment]
@ferrarimarco Sorry for the late response. But yes, its an xsd extension. Now you've created the PR to fix this, do I have to wait for it to be merged before I can test again ?

**Comment by ferrarimarco** [comment]
No worries! You're correct :)
