### ISSUE TITLE
tflint error encountered while scanning stdout

### ISSUE THREAD

**Issue by pfuhrmann** [super-linter/super-linter#5253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

tflint fails due to read error on parallel runs (suspected reason, because on v5 it works).

### Expected Behavior

tflint should not fail with the read error.

### Super-Linter version

```markdown
v6.0.0
```

### Relevant log output

```shell
22:49:30 [INFO]  go-plugin@v1.6.0/client.go:780: plugin process exited: plugin=/root/.tflint.d/plugins/github.com/terraform-linters/tflint-ruleset-azurerm/0.25.1/tflint-ruleset-azurerm id=11159
  Error: 0 [ERROR] go-plugin@v1.6.0/client.go:804: error encountered while scanning stdout: error="read |0: file already closed"
  22:49:30 [INFO]  go-plugin@v1.6.0/client.go:780: plugin process exited: plugin=/root/.tflint.d/plugins/github.com/terraform-linters/tflint-ruleset-google/0.26.0/tflint-ruleset-google id=11165
```

### Steps To Reproduce

1. Have a multiple folders with TF configs
2. Run super-linter in GA
3. See the log above

### Anything else?

- I suspect this is the reason: https://github.com/super-linter/super-linter/pull/5177
- Tested on [v5.7.2](https://github.com/super-linter/super-linter/releases/tag/v5.7.2) and it works fine.
- Tested also locally using Docker image, same issue on `v6.0.0`
- Could we add perhaps an option to disable parallel runs or to configure parallelism?

**Comment by pfuhrmann** [comment]
1. `docker run --rm -e RUN_LOCAL=true -e DEFAULT_BRANCH=main  -v "$(pwd)":/tmp/lint ghcr.io/super-linter/super-linter:v6.0.0`
2. Sorry, I cannot do that because it would contain sensitive information which I cannot share.
3. We have a single folder in the repository called `terraform` which contains ~20 additional folders, each containing HCL files (separate backends, handling different parts of infrastructure). It's ~10k (HCL) LOC. Please ask for more details if you need to know anything more specific.

With all the above said, this might be not an issue with super-linter. Found out this: https://github.com/hashicorp/go-plugin/issues/298, and it got recently upgraded in `tflint`: https://github.com/terraform-linters/tflint/pull/1846.

**Comment by ferrarimarco** [comment]
Ah! Thanks for the research. That might be it :)

Closing this for now.
