### ISSUE TITLE
v6 branch?

### ISSUE THREAD

**Issue by JoeLyga** [super-linter/super-linter#5289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Are there any plans to add a v6 branch that stays continuously up to date?  Previously I had my yaml pointed at `@v5`.  But to use the new stuff I have to add the specific release.  Thanks!

### Expected Behavior

I would expect there to be a `@v6` tag to keep up to date with the current releases.

### Anything else?

Thanks for super-linter, works great!

**Comment by ferrarimarco** [comment]
Hi @JoeLyga ! Did you try with `v6`?

Earlier today we fixed an issue with our release workflow (#5284).

**Comment by JoeLyga** [comment]
Works great, thanks!
