### ISSUE TITLE
CHECKOV Linter does not respect `VALIDATE_ALL_CODEBASE`

### ISSUE THREAD

**Issue by mcanouil** [super-linter/super-linter#5308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Within GitHub Action workflow using `VALIDATE_ALL_CODEBASE: false`, the CHECKOV linter is scanning files outside of the files added/modified by the pull request.

### Expected Behavior

CHECKOV linter should respect `VALIDATE_ALL_CODEBASE` as the other linters.

### Super-Linter version

```markdown
v6.1.1
```

### Relevant log output

See <https://github.com/mcanouil/super-linter-checkov/actions/runs/7961206354/job/21731881369>.
Triggered by https://github.com/mcanouil/super-linter-checkov/pull/1 pull request which only adds a `README.md` thus no Dockerfile.

### Steps To Reproduce

See <https://github.com/mcanouil/super-linter-checkov>.

**Comment by ferrarimarco** [comment]
Hi @mcanouil !

This is expected, in the current implementation because Checkov needs to lint entire directories, not just standalone files, so we would need to address those corner cases, which is work that we cannot easily automate or streamline.

What are you trying to achieve?

**Comment by ferrarimarco** [comment]
You can achieve what you need with the Checkov "baseline" feature. It's somewhat documented in the [Checkov CLI command reference](https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html). By establishing a baseline (of known failing checks), you can introduce Checkov in a legacy codebase.

Example: https://github.com/super-linter/super-linter/blob/main/.github/linters/.checkov.yaml and https://github.com/super-linter/super-linter/blob/main/.github/linters/.checkov.baseline.

You can generate a baseline file by opening a shell in a super-linter container [running locally](https://github.com/super-linter/super-linter/blob/main/docs/run-linter-locally.md), and then run:

```sh
checkov --create-baseline --directory /tmp/lint
```

Hopefully, this will point you in the right direction.

**Comment by mcanouil** [comment]
Thanks, not exactly the expected answer but this will do.

For the future, could some changes like this one be listed as breaking changes? If a feature makes the workflow behaves differently that one can expect when using `VALIDATE_ALL_CODEBASE`, it should really be stated.

**Comment by nantiferov** [comment]
Is there a reason why CHECKOV is enabled by default if it breaks assumption that with `VALIDATE_ALL_CODEBASE: false` will be checked only changed?

**Comment by nantiferov** [comment]
I saw this.
My question is why it's enabled by default?

**Comment by mcanouil** [comment]
Indeed, the explanation only state what CHECKOV does but does not explain why you are willing to break workflows by enabling it by default.

**Comment by ferrarimarco** [comment]
You can disable this linter (as any other), and that it also support configuring a "baseline" so you don't have to fix everything before enabling it. If there's anything that's preventing this from working, please file a new bug, we'll happily review it.

All linters are enabled by default, since the early super-linter days, and Checkov is not a special case in that regard. Imagine that a lInter adds a new check (this happens all the time) that might flag issues that it previously ignored. So workflows that run that linter (using super-linter or otherwise) will now report failures. I don't think that they are breaking workflows, but rather the opposite: they are doing their job, unless you explicitly disable them, or ignore specific checks.

**Comment by ferrarimarco** [comment]
PS: other linters that are designed to run against directories instead of individual files are implemented this way, such as ansible-lint

**Comment by mcanouil** [comment]
> All linters are enabled by default, since the early super-linter days, and Checkov is not a special case in that regard. 

That is the explanation.

When a directory level linter is added, could there be a section in the documentation to list the linter that does not follow `VALIDATE_ALL_CODEBASE`?

**Comment by ferrarimarco** [comment]
Ah! That's a nice proposal. I'll happily review a PR for that.

**Comment by mcanouil** [comment]
I would have done it, although I would have to look at all the linters which I don't know nearly anything about to make such list.
