### ISSUE TITLE
Output does not escape GitHub Actions log markers/commands

### ISSUE THREAD

**Issue by jantmanAtCox** [super-linter/super-linter#5343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If one of the linters finds a problem in code that includes GitHub Actions log markers such as `##[group]`, those are passed straight through to the output and result in very confusing output from the job.

![Screenshot 2024-02-29 at 2 16 10 PM](https://github.com/super-linter/super-linter/assets/157712692/c6d7176c-cda5-423e-9ba5-2fcc55dbe373)

### Expected Behavior

GitHub Actions log markers such as `##[group]`, `::debug::`, `::notice`, `::group::` and `::endgroup::`, etc. are escaped so that they don't alter the presentation of the logs.

### Super-Linter version

```markdown
v6.3.0
```

### Relevant log output

```shell
None that can be pasted in a useful way.
```

### Steps To Reproduce

1. Have some source code that includes both GitHub Actions log markers such as `##[group]` and ``##endgroup`` as well as linting issues, such as the snippet included below.
2. Run the super-linter GitHub Action on it, and look at the output log.

### Anything else?

Here's a snippet of Python that triggers this issue, taken from an internal application that parses GitHub Actions workflow logs:

```python
    def _split_step_log_in_groups(self, content: str) -> List[str]:
        """
        Strip timestamps from the front of each line, then parse each group from
        the output and return an array of the groups (or non-group parts).
        """
        content = self.TIMESTAMP_RE.sub('', content)
        groups: List[str] = []
        buffer: List[str] = []
        for line in content.split('\n'):
            if line.startswith('##[group]'):
                if buffer:
                    groups.append('\n'.join(buffer))
                    buffer = []
                buffer.append(line)
            elif line.startswith('##[endgroup]'):
                buffer.append(line)
                groups.append('\n'.join(buffer))
                buffer = []
            else:
                buffer.append(line)
        if buffer:
            groups.append('\n'.join(buffer))
        return [g for g in groups if g.strip() != '']

    def _handle_step_asa(self, filename: str, content: str) -> bool:
      # lint
        gstart: str = '##[group]Run some-action'
        if gstart not in content:
            return False
         # redacted from here on

    def _handle_step_foo(
        self, filename: str, content: str
    ) -> bool:
       # more lint
        gstart: str = '##[group]Run cai-actions/change-request-create'
        if gstart not in content:
            return False
```

**Comment by ferrarimarco** [comment]
Hi @jantmanAtCox !

I wouldn't classify this as a bug, because it's not a currently supported use case that is broken. This of course doesn't prevent us to improve things!

I'll be happy to review a PR for this one.
