### ISSUE TITLE
ESLint parsing errors excluded from Annotations

### ISSUE THREAD

**Issue by brendonrapp** [super-linter/super-linter#5363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ESLint output counts both errors from rule violations as well as parsing errors (see: 9 errors, 10 warnings):

![errors-1](https://github.com/super-linter/super-linter/assets/170030/0425f1a1-2fe2-4971-874b-b890bc0dc974)

But the Annotations created exclude the parsing error (see: 8 errors, 10 warnings):

![errors-2](https://github.com/super-linter/super-linter/assets/170030/c713a562-1ad9-485e-90d5-9ad7f874ad62)

### Expected Behavior

I would expect parsing errors to be annotated, exactly like rule violations.

### Super-Linter version

```markdown
v6.3.0
```

### Relevant log output

```shell
In attached screenshots.
```

### Steps To Reproduce

1. Lint JS files with eslint that contain parsing errors.
2. Note the exclusion of these errors from the Annotations

**Comment by ferrarimarco** [comment]
Hi there! Annotations are added by each tool individually, not by super-linter. I would try reproducing this running eslint outside super-linter, and eventually opening an issue in the eslint repository.
