### ISSUE TITLE
ignore avif image files in BuildFileList

### ISSUE THREAD

**Issue by joshunger** [super-linter/super-linter#5382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I noticed we're ignoring `webp` image files but not `avif` image files in `BuildFileList` https://github.com/super-linter/super-linter/blob/main/lib/functions/buildFileList.sh#L78

### Expected Behavior

Shouldn't we also ignore `.avif` image files?

### Super-Linter version

```markdown
5
```

### Relevant log output

```shell
N/A.
```

### Steps To Reproduce

N/A.

**Comment by ferrarimarco** [comment]
Hi @joshunger ! Feel free to send a PR to add that. I'll happily review it :)

**Comment by ferrarimarco** [comment]
#5604 should take care of this
