### ISSUE TITLE
BASH_SEVERITY not working

### ISSUE THREAD

**Issue by matbun** [super-linter/super-linter#5412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

BASH_SEVERITY does not filter the lower severity errors (e.g., "info"), when BASH_SEVERITY=warning

### Expected Behavior

BASH_SEVERITY should filter the lower severity errors (e.g., "info"), when BASH_SEVERITY=warning

### Super-Linter version

```markdown
slim-v5.0.0
```

### Relevant log output

```shell
2024-03-20 17:33:39 [INFO]   File:[/github/workspace/tutorials/distributed-ml/tutorial-0-basics/ddp_slurm.sh]
2024-03-20 17:33:39 [ERROR]   Found errors in [shellcheck] linter!
2024-03-20 17:33:39 [ERROR]   Error code: 1. Command output:
------

In /github/workspace/tutorials/distributed-ml/tutorial-0-basics/ddp_slurm.sh line 27:
source ../../../envAI_hdfml/bin/activate
       ^-- SC1091 (info): Not following: ../../../envAI_hdfml/bin/activate: openBinaryFile: does not exist (No such file or directory)

For more information:
  https://www.shellcheck.net/wiki/SC1091 -- Not following: ../../../envAI_hdf...
------
2024-03-20 17:33:39 [INFO]   ---------------------------
```

### Steps To Reproduce

See this GH action run (e.g., L316): https://github.com/interTwin-eu/itwinai/actions/runs/8363368499/job/22896129844?pr=117

Note the workflow file here: https://github.com/interTwin-eu/itwinai/actions/runs/8363368499/workflow?pr=117
and that `BASH_SEVERITY: warning`

**Comment by ferrarimarco** [comment]
Hi @matbun !

Can you please try again with the latest super-linter version, and provide a debug log?

Thanks!

**Comment by matbun** [comment]
Moving from `uses: github/super-linter/slim@v5` to `uses: super-linter/super-linter/slim@v6.3.0` solved the issue.
