### ISSUE TITLE
Clang Format Config File

### ISSUE THREAD

**Issue by umitbuyukulcay** [super-linter/super-linter#5413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Super-linter does not able to consider clang-format style files

### Expected Behavior

Clang-Format can be consider style file.

**Comment by ferrarimarco** [comment]
Hi @umitbuyukulcay !

I think we might need more information about your use case. What are you trying to achieve? Can you also add an example?

Thanks!

**Comment by umitbuyukulcay** [comment]
I mean, clang-format uses llvm format style as default. On the other hand, clang-format has -style flag to let us to determine rules for formating styles. I want to use my own style and wanna check it with clang-format without based on llvm. It could be better to add give config to clang-format with ".clang-format" file. documentation in [ here](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) 
thanks.

**Comment by ferrarimarco** [comment]
I think this is a fair request. Adding it to the backlog.

I'll happily review a PR for this.
