### ISSUE TITLE
Update Python Test Files

### ISSUE THREAD

**Issue by Okabe-Junya** [super-linter/super-linter#5501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Super-linter supports several Python linters and formatters. However, the contents of the test files differ between ruff and the others.

FYI: https://github.com/super-linter/super-linter/tree/e71a37d49d588b33a0d6e10f364a682e7704460e/test/linters

### Expected Behavior

For all Python tools, the same test files should be used. Moreover, they should be simple (meaning, it would be better to align them with the test files for ruff).

### Anything else?

Comment from ferrarimarco in #5456: https://github.com/super-linter/super-linter/pull/5456#issuecomment-2039055229, https://github.com/super-linter/super-linter/pull/5456#discussion_r1553245110

**Comment by Okabe-Junya** [comment]
I'll work on this issue, thanks!!

**Comment by ferrarimarco** [comment]
Thanks @Okabe-Junya !
