### ISSUE TITLE
Unable to remove .ruff_cache folder

### ISSUE THREAD

**Issue by alexanderbazhenoff** [super-linter/super-linter#5543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, again folder permissions when using standalone docker image in GitLab CI. This time `.ruff_cache` owned by root.

```
warning: failed to remove .ruff_cache/0.3.7/17270506990096333443: Permission denied
warning: failed to remove .ruff_cache/CACHEDIR.TAG: Permission denied
warning: failed to remove .ruff_cache/.gitignore: Permission denied
```

### Expected Behavior

Why not to store all these temporary/cache files inside docker container by default? (instead of adding `sudo rm -rf <new_path>` to `before_script` on every version update :)

### Anything else?

Thanks in advance for any ideas.

**Comment by ferrarimarco** [comment]
#5548 should take care of this

**Comment by alexanderbazhenoff** [comment]
@ferrarimarco thanks for the quick response!

**Comment by Okabe-Junya** [comment]
Thank you for this PR as the contributor who opened #5456 ;) #5548 Looks Good to me!!
