### ISSUE TITLE
`docs/disabling-linters.md` removed in `v6` — is this expected?

### ISSUE THREAD

**Issue by yermulnik** [super-linter/super-linter#5657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/super-linter/super-linter/blob/main/docs/disabling-linters.md does not exist abymore.
Still exists with `v5`: https://github.com/super-linter/super-linter/blob/v5/docs/disabling-linters.md

### Expected Behavior

https://github.com/super-linter/super-linter/blob/main/docs/disabling-linters.md exists

**Comment by yermulnik** [comment]
[PR](https://github.com/super-linter/super-linter/pull/4981) that removed the file had no distinct statement on this specific file, which was, well, useful for beginners 😢

**Comment by ferrarimarco** [comment]
Hi @yermulnik ! You can find up-to-date information about that topic in the [main README](https://github.com/super-linter/super-linter?tab=readme-ov-file#configure-linters)

**Comment by yermulnik** [comment]
@ferrarimarco Oh, my bad, I missed that bit. Apologies and thanks for the pointer.
