### ISSUE TITLE
Propose: BASH_EXEC_IGNORE_LIBRARIES be true by default

### ISSUE THREAD

**Issue by jasonkarns** [super-linter/super-linter#5731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Present behavior makes superlinter do the "wrong thing" by default (ie, with the default configuration).

Given a codebase that contains any of:
- library scripts
- shell profile/rc scripts
- bats tests
- shell test helpers (`test/test_helper.sh`)
- .env files with modelines

superlinter will fail because none of these files are (nor should they be) executable. They aren't _supposed_ to be executable (which is why they don't have shebangs).

### Expected Behavior

My expectation is that `BASH_EXEC_IGNORE_LIBRARIES` be true by default: superlinter should only check the executable bit for files that are indicated as being executable (ie, have a shebang).

It would be very much preferable for this option to be the default so that users can leverage superlinter the most straightforward way. (This is especially true when using superlinter through a reusable workflow where the "config" env vars may not already be exposed/respected to the calling workflows.)

I would expect codebases that deviate from the convention need to opt-in to the contrarian behavior. (Especially for a linter whose sole purpose is to strengthen established conventions.)

### Anything else?

Rationale on the file extension convention: Files with extensions are "sourced" by the interpreter that maps to that extension. eg. `foo.rb` is "sourced" by ruby via `ruby foo.rb`. Files that are executable use shebangs _so the interpreter can be changed without affecting users_. `foo` may be written in ruby initially, but as an executable, one may desire to rewrite it to perl or python. (Git is famous for having executables start as executable perl scripts that are later converted to C.) Similarly, in general, foo.bash is intended to be sourced, whereas foo is executable with a shebang.

ruby gem executables don't have a file extension, npm-package executables don't have a file extension. binstubs generated by bundler don't have a file extension. nor virtually any file in `bin/*`. Or the [scripts-to-rule-them-all](https://github.com/github/scripts-to-rule-them-all) pattern.

The scenarios where a with-extension file is executable are the exception, rather than the rule. (And even in those cases, a good many only do so because the file is able to be sourced/imported/required _as well as_ executed.) super linter should be enforcing the rule, not the exception.

Bug first filed: https://github.com/super-linter/super-linter/issues/5212
Env var added: https://github.com/super-linter/super-linter/pull/5254

**Comment by bewuethr** [comment]
Here's an [opinionated classic](https://www.talisman.org/~erlkonig/documents/commandname-extensions-considered-harmful/) about the topic.

**Comment by jasonkarns** [comment]
Somewhat implicit in the above propose but I'll make it slightly more explicit:

I (strongly) believe it is in the interests of linters to have the most useful default configurations such that _out of the box_ they guide towards the common convention. Each additional configuration option that is required is a divergence from the idiomatic/conventional and thus a detraction from one of the values of linting: consistency.

(In cases where a convention is not clear or still rather contested, it is in the interest of the linter to abstain from an opinion entirely so as to preserve the primacy of the linter's default configuration.)

**Comment by ferrarimarco** [comment]
(just noting that if we decide to go ahead with this, it's going to be a breaking change)

**Comment by ferrarimarco** [comment]
A [quick code search](https://github.com/search?q=BASH_EXEC_IGNORE_LIBRARIES&type=code) shows 5 instances of workflows that set `BASH_EXEC_IGNORE_LIBRARIES` to `true`. Seems like that most people are happy with the current defaults?

**Comment by jasonkarns** [comment]
> (just noting that if we decide to go ahead with this, it's going to be a breaking change)
I'm not sure I'd agree with this. Flipping the default would be _relaxing_ the linter, not strengthening it. So changing it would not make existing-valid codebases suddenly start failing the linter. (I presume that's the breaking-change guideline? a green build should not become red by a super-linter patch|minor bump?)

> A [quick code search](https://github.com/search?q=BASH_EXEC_IGNORE_LIBRARIES&type=code) shows 5 instances of workflows that set `BASH_EXEC_IGNORE_LIBRARIES` to `true`. Seems like that most people are happy with the current defaults?

That's not a safe assumption to draw from that search or results.

1. this option is less than 4 months old. there are thousands of configurations of super-linter that are not on a version that even has this option. (my count after searching is somewhere near 10k instances pinned to v5 or lower)
2. quick search for `VALIDATE_BASH_EXEC` has 300+ results (many of them not necessarily setting to false, but since the default is true the vast majority probably are). Anyone who disables the linter entirely wouldn't need to ignore libs.
2. 9000 results for `VALIDATE_ALL_CODEBASE` could also make it unnecessary to set `BASH_EXEC_IGNORE_LIBRARIES` directly.
3. only super-linter v6 triggers errors for this linter. the thousands of configurations pinned to v5 or lower would have no need set set this in the first place. (my count after searching is somewhere near 10k instances pinned to v5 or lower)

**Comment by bewuethr** [comment]
> > Flipping the default would be _relaxing_ the linter
> 
> This is a breaking change because it's a change in the default configuration. Users might be relying on the current default behavior.

But since it's relaxing, doesn't that mean that there is no repo out there that passes today, but would fail if the default were changed?

**Comment by jasonkarns** [comment]
> Users might be relying on the current default behavior.

I don't want to quibble on this too much, because I don't really care (to the extend that it doesn't affect whether the change is accepted). But I don't think that's a realistic definition of breaking change. If that's the definition of breaking change, then there is no such thing as minor or patch changes, because users could depend on bugs and be broken when a patch is released. Or depend on a method _not_ being defined in an api, and suddenly break when a new feature is released. I've personally seen an app break when an additional method parameter was added to a dep's api. (technically that's a new feature!) The client code was already (accidentally) sending an additional parameter. So their code "depended on" the public api only accepting 2 params and disregarding the third; when the 3rd param was added, the client broke! (This is an absurd example. But it's true. If we follow Hyrum's Law for versioning, breaking-change major versions is all there would ever be.)

So we should probably not look at it in the abstract. This project doesn't bump the major version when new lint rules are added (otherwise it'd be on v453 or something very high). So "keeping green builds green" must not be the rule. If we look at this rule specifically, a script that is supposed to be executable but _doesn't_ have a shebang is broken. So anyone who is relying on this linter to arbitrary make every shell-script-looking-file executable is already broken.

A better way to look at it: the linter is currently reporting false positives. It is incorrectly flagging valid/correct code as "erronous". That is a bug in the linter. So flipping the default is a bugfix so that superlinter stops flagging _correct_ code as an error.

But truthfully, I'll be able to bump to whatever new version of superlinter fixes this bug. I'm not concerned about how the fix is made. I would just like superlinter to stop (incorrectly) presuming that every shell script is supposed to be executable. It's not true of any other script (ruby, python, perl or javascript) and it's never been true of shell scripts either.

**Comment by ferrarimarco** [comment]
> > Users might be relying on the current default behavior.
> 
> I don't want to quibble on this too much, because I don't really care (to the extend that it doesn't affect whether the change is accepted). But I don't think that's a realistic definition of breaking change. Users and apps depend on bugs, too. By that definition, every release would be a breaking change. (Which is really just acknowledgement of Hyrum's Law.)

Depending on a bug (even without realizing it) is different from depending on a feature. A feature has an intended and (hopefully) documented behavior. We're discussing about changing that behavior.

What makes this a breaking change is that it's unlikely that we can implement it in a backward-compatible way, given that we're chaging the default value of a configuration value.

> A better way to look at it: the linter is currently reporting false positives. It is incorrectly flagging valid/correct code as "erronous". That is a bug in the linter. So flipping the default is a bugfix so that superlinter stops flagging _correct_ code as an error.

From the Super-linter point of view, this is not a bug because the feature is working as intended.

However, I wouldn't spend too much time about discussing if this is a breaking change, a non-breaking change, or a bug to fix. I would prefer to focus on your next point, that is the essence of the issue. We can decide about the nature of the change once we have a better idea of how we can possibly implement it.

> But truthfully, I'm not concerned about how the fix is released. I would just like superlinter to stop (incorrectly) presuming that every shell script is supposed to be executable.

What makes this incorrect? For example, [Bash reference manual](https://www.gnu.org/software/bash/manual/bash.html#Shell-Scripts) doesn't recommend either, and explains what happens in both cases. I suppose this is a matter of style and convention.

> It's not true of any other script with a file extension (ruby, python, perl, javascript etc) and it's never been true of shell scripts either.

This is true, although unrelated to this discussion because the interpreters of these scripts don't usually complain about a scripts being or not being executable.
