### ISSUE TITLE
goreleaser failing with [FATAL] when it shoud be disabled and there is no GO code in project

### ISSUE THREAD

**Issue by damies13** [super-linter/super-linter#5902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

I am trying to upgrade from super-linter@v4 to super-linter@v6, and I am getting a [FATAL] from goreleaser as below:
```
  goreleaser:   ____       ____      _
   / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
  | |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
  | |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
   \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
  goreleaser: Deliver Go Binaries as fast and easily as possible

.
.
.
  2024-07-18 23:46:53 [INFO]   The master branch doesn't exist in /github/workspace
  2024-07-18 23:46:53 [INFO]   The origin/master branch doesn't exist in /github/workspace
  2024-07-18 23:46:53 [FATAL]   Neither master, nor origin/master exist in /github/workspace

```

As my project is pure python, I have no need for goreleaser, so added the following to superlinter:
```
        env:
          DEFAULT_BRANCH: master
          VALIDATE_GO: false
          VALIDATE_GO_MODULES: false
          VALIDATE_GO_RELEASER: false

```

However goreleaser still fails with a [FATAL]

### Expected Behavior

goreleaser should not be running

### Super-Linter version

```markdown
super-linter@v6
ghcr.io/super-linter/super-linter:v6.4.1
```

### Relevant log output

```shell
goreleaser:   ____       ____      _
   / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
  | |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
  | |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
   \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
  goreleaser: Deliver Go Binaries as fast and easily as possible

.
.
.
  2024-07-18 23:46:53 [INFO]   The master branch doesn't exist in /github/workspace
  2024-07-18 23:46:53 [INFO]   The origin/master branch doesn't exist in /github/workspace
  2024-07-18 23:46:53 [FATAL]   Neither master, nor origin/master exist in /github/workspace

```
```


### Steps To Reproduce

1. Upgrade from super-linter@v4 to super-linter@v6 on a python project

### Anything else?

no

**Comment by ferrarimarco** [comment]
Hi! It's not Go releaser. The error is about the default branch missing:

```
2024-07-18 23:46:53 [FATAL]   Neither master, nor origin/master exist in /github/workspace
```

**Comment by damies13** [comment]
Well the first issue then is there is no indication which linter produced this error if it's not goreleaser, I logged it as a goreleaser issue as that was the last linter that identified itself

The second issue is the master branch exists, so I don't understand why it thinks it's missing, this error makes no sense at all, this error provides no link or clue to further information or what's required to resolve it.
- When I google the error I don't get any further explanation.
- I also referred to the [upgrade guide](https://github.com/super-linter/super-linter/blob/main/docs/upgrade-guide.md), which also had no mention of this error or how to deal with it.

I resolved it for now by rolling back to v5 (which is still newer than v4 that I was on). 

Until I know how to resolve this issue I can't update to v6.

Sorry this should not be closed as it's not resolved, please re-open

**Comment by ferrarimarco** [comment]
Hi! Please open a new issue by completing all the fields, including your full Super-linter configuration, otherwise it's hard to understand what is going on.
