### ISSUE TITLE
Use .prettierrc 

### ISSUE THREAD

**Issue by MaxymGorn** [super-linter/super-linter#5956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't use .prettierrc for JS

### Expected Behavior

For Javascript Prettier is there a way to set the rules for prettier? I don't see anything in TEMPLATES dir

**Comment by ferrarimarco** [comment]
Hi! Prettier should pick the configuration file automatically without the need of configuring it.

**Comment by MaxymGorn** [comment]
I just have general question, how I can pass env variables for standardjs or via package.json:: 
<img width="710" alt="image" src="https://github.com/user-attachments/assets/da9423a7-efc4-4a0e-88ca-de35f0cb1201">
