### ISSUE TITLE
v6.8.0 fails `TYPESCRIPT_STANDARD` with Parsing error

### ISSUE THREAD

**Issue by tbright92** [super-linter/super-linter#5979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

Getting the following error on some, but not all, .ts files after using v6.8.0
`Parsing error: '{' expected. (null)` on line 0:0

Even creating a new, empty file throws this error.

Reverting to v6.7 fixes the issue.

### Expected Behavior

v6.8 should not encounter this error for the TYPESCRIPT_STANDARD check.

### Super-Linter version

```markdown
v6.8.0
```

### Super-linter configuration

```yaml
- name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Package Dependencies
        run: |
          npm install @angular-eslint/eslint-plugin@17.2.1
          npm install @angular-eslint/eslint-plugin-template@17.2.1
          npm install @angular-eslint/schematics@17.2.1
          npm install @angular-eslint/template-parser@17.2.1
          npm install @typescript-eslint/eslint-plugin@6.21.0
          npm install @typescript-eslint/parser@6.21.0
          npm install jsonc-eslint-parser@2.4.0

      - name: Super-linter
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GENERATED_FILES: true
          JAVASCRIPT_DEFAULT_STYLE: prettier
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_BASH_EXEC: false
```

### Relevant log output

```shell
2024-08-01 02:21:29 [INFO]   Linting TYPESCRIPT_STANDARD items...
  Error: -01 02:21:41 [ERROR]   Found errors when linting TYPESCRIPT_STANDARD. Exit code: 1.
  2024-08-01 02:21:41 [INFO]   Command output for TYPESCRIPT_STANDARD:
  ------
    /github/workspace/Wex.Funding.FundManager/Wex.Funding.FundManager.Client/src/app/fund/components/shared/entity-group-form/entity-group-form-tests/entity-group-form-edit.component.spec.ts:0:0: Parsing error: '{' expected. (null)
    /github/workspace/Wex.Funding.FundManager/Wex.Funding.FundManager.Client/src/app/fund/components/shared/entity-group-form/entity-group-form.component.ts:0:0: Parsing error: '{' expected. (null)
  ------
  2024-08-01 02:21:41 [INFO]   Stderr contents for TYPESCRIPT_STANDARD:
  ------
  ts-standard: Standard for TypeScript! (https://github.com/standard/ts-standard)
  ------
```

### Steps To Reproduce

I'm trying to reproduce locally, but having trouble getting the super-linter to run identically to our pipeline. I will hopefully be able to update this section soon.

**Comment by ferrarimarco** [comment]
Hi!

Super-linter `v6.8.0` fixed a confusing corner case and documented some variables that were missing from the configuration. Can you try following the [section about this in the upgrade guide](https://github.com/super-linter/super-linter/blob/main/docs/upgrade-guide.md#javascript_default_style-and-typescript_default_style)?

**Comment by ferrarimarco** [comment]
Closing as a configuration issue. We'll reopen if new data points come up. :)
