### ISSUE TITLE
FILTER_REGEX_INCLUDE not working as expected

### ISSUE THREAD

**Issue by missAnkita** [super-linter/super-linter#6014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [X] I think that this is a Super-linter issue.

### Current Behavior

I am passing below 2 env to my super linter action:

file: /.github/workflows/super-linter-resuable-wf.yml
- name: Super Linter Code Base
        uses: missAnkita/Reusable-Workflows/.github/actions/Super-Linter@main
        with:
          working-directory: ${{ inputs.working-directory }}
        env:
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: '${{ inputs.working-directory }}/.*\\.(cs|js|sh)$'

Filename: .github/actions/Super-Linter/action.yml    
name: Super Linter action
description: Super Linter action for Azure functions dotnet application
runs:
  using: "composite"
  steps:
    - id: lint
      name: Super Linter Code base run
      uses: super-linter/super-linter@v5  

But while running it says "No files were found in the GITHUB_WORKSPACE:[/github/workspace] to lint!"
Note: for testing i even added and even edited one file to lint in source repo.

### Expected Behavior

Lint the new files added in the  inputs.working-directory

### Super-Linter version

```markdown
Status: Downloaded newer image for ghcr.io/super-linter/super-linter:v5
  ghcr.io/super-linter/super-linter:v5
```

### Super-linter configuration

```yaml
- name: Super Linter Code Base
        uses: missAnkita/Reusable-Workflows/.github/actions/Super-Linter@main
        with:
          working-directory: ${{ inputs.working-directory }}
        env:
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: '${{ inputs.working-directory }}/.*\\.(cs|js|sh)$'
```

### Relevant log output

```shell
Run missAnkita/Reusable-Workflows/.github/actions/Super-Linter@main
Run super-linter/super-linter@v5
  env:
    VALIDATE_ALL_CODEBASE: false
    FILTER_REGEX_INCLUDE: /home/runner/work/azure_functions_app1/azure_functions_app1/.*\\.(cs|js|sh)$
/usr/bin/docker run --name ghcriosuperlintersuperlinterv5_dbb4e8 --label 7681dc --workdir /github/workspace --rm -e "VALIDATE_ALL_CODEBASE" -e "FILTER_REGEX_INCLUDE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "GITHUB_ACTION_PATH" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/azure_functions_app1/azure_functions_app1":"/github/workspace" ghcr.io/super-linter/super-linter:v5
--------------------------------------------------------------------------------

                              /@@#///////@@/(@//@%/(@.@(       @@
                          @@//////////////////////////////#*  @@@
                        @////@//(///////////@@@@@///@//@/@**//@@(
                      @///////@///////////////@@@@    (           @,
                     @/(&/@////////////////////                     @
                    @////////////////////////@@                      @
                  @%////////(//////////%/////&@            @@       *,@           ______________
             @@@@@/@/#/////(&//////////////////                       .@         /              \
        *@@@@@.    .%///(//@//////////////////&.   .@@,                 @%      / Don't mind me  \
      @@%           .&@&&/@.@//&/////(//////////    @@@@@@@@@         .. &@    / I'm just looking \
    @@%               @@@@@   @&/////////////////#   @/       V  @@/ ,@@@ @   <  for some trash... |
@@@%                   @@@@        .%@@@@//////#@ @   @@         @     .,.     \__________________/
                                          @@@/@(  (@@@@% @/\      %
                                           @@@@(    .     .@@/\   #
                                             @                  %@%

--------------------------------------------------------------------------------
2024-08-13 06:49:05 [INFO]   ---------------------------------------------
2024-08-13 06:49:05 [INFO]   --- GitHub Actions Multi Language Linter ----
2024-08-13 06:49:05 [INFO]    - Image Creation Date:[2023-12-02T08:58:56Z]
2024-08-13 06:49:05 [INFO]    - Image Revision:[a8150b40c89574adb5f68bf9502b890a236a06b3]
2024-08-13 06:49:05 [INFO]    - Image Version:[a8150b40c89574adb5f68bf9502b890a236a06b3]
2024-08-13 06:49:05 [INFO]   ---------------------------------------------
2024-08-13 06:49:05 [INFO]   ---------------------------------------------
2024-08-13 06:49:05 [INFO]   The Super-Linter source code can be found at:
2024-08-13 06:49:05 [INFO]    - https://github.com/super-linter/super-linter
2024-08-13 06:49:05 [INFO]   ---------------------------------------------
2024-08-13 06:49:05 [INFO]   --------------------------------------------
2024-08-13 06:49:05 [INFO]   Gathering GitHub information...
2024-08-13 06:49:05 [INFO]   Successfully found:[GITHUB_SHA], value:[d7bdd61dbc9f1bc7abd9da5245fd6e09ca18cf83]
2024-08-13 06:49:05 [INFO]   Successfully found:[GITHUB_WORKSPACE], value:[/github/workspace]
2024-08-13 06:49:05 [INFO]   Successfully found:[GITHUB_EVENT_PATH], value:[/github/workflow/event.json]
2024-08-13 06:49:05 [INFO]   Successfully found:[GITHUB_ORG], value:[missAnkita]
2024-08-13 06:49:05 [INFO]   Successfully found:[GITHUB_REPO], value:[azure_functions_app1]
2024-08-13 06:49:05 [ERROR]   Failed to get [GITHUB_TOKEN]!
2024-08-13 06:49:05 [ERROR]   []
2024-08-13 06:49:05 [ERROR]   Please set a [GITHUB_TOKEN] from the main workflow environment to take advantage of multiple status reports!
2024-08-13 06:49:05 [INFO]   --------------------------------------------
2024-08-13 06:49:05 [INFO]   Gathering user validation information...
2024-08-13 06:49:05 [INFO]   - Only validating [new], or [edited] files in code base...
2024-08-13 06:49:10 [WARN]   No files were found in the GITHUB_WORKSPACE:[/github/workspace] to lint!
2024-08-13 06:49:10 [INFO]   ---------------------------------
2024-08-13 06:49:10 [INFO]   ------ File list to check: ------
2024-08-13 06:49:10 [INFO]   ---------------------------------
2024-08-13 06:49:10 [INFO]   ----------------------------------------------
2024-08-13 06:49:10 [INFO]   Successfully gathered list of files...
2024-08-13 06:49:13 [INFO]   ----------------------------------------------
2024-08-13 06:49:13 [INFO]   ----------------------------------------------
2024-08-13 06:49:13 [INFO]   The script has completed
2024-08-13 06:49:13 [INFO]   ----------------------------------------------
2024-08-13 06:49:13 [INFO]   ----------------------------------------------
2024-08-13 06:49:13 [NOTICE]   All file(s) linted successfully with no errors detected
2024-08-13 06:49:13 [INFO]   ----------------------------------------------
Run echo "$FILTER_REGEX_INCLUDE"
/home/runner/work/azure_functions_app1/azure_functions_app1/.*\\.(cs|js|sh)$
```

### Steps To Reproduce

it should work as given in the official docs

**Comment by ferrarimarco** [comment]
Hi! I think this is a configuration issue because `${{ inputs.working-directory }}` is not where the container working directory is mounted, because it gets mounted on the path specified by `DEFAULT_WORKSPACE`.

I suggest trying by removing `${{ inputs.working-directory }}`.

Also, what you trying to achieve? It looks like you're filtering by file extension only, so it might be easier to remove it, and use `VALIDATE_xxxx` to enable only the linters and formatters that you need.

**Comment by missAnkita** [comment]
Hi, it still gives below message:

 Gathering user validation information...
2024-08-13 09:35:44 [INFO]   - Only validating [new], or [edited] files in code base...
2024-08-13 09:35:[48](https://github.com/missAnkita/azure_functions_app1/actions/runs/10367237897/job/28698343827#step:6:50) [WARN]   No files were found in the GITHUB_WORKSPACE:[/github/workspace] to lint!

to test this i edited one file in source code repo.

**Comment by ferrarimarco** [comment]
Please, try re-running the workflow with debug logging enabled. After that, can you please provide a link to the workflow run with debug logging enabled, so we can have a look? Thanks!

**Comment by missAnkita** [comment]
ok sure

**Comment by missAnkita** [comment]
https://github.com/missAnkita/azure_functions_app1/actions/runs/10367446572/job/28698908700

here i removed all variables previously given variables. That means its scanning entire code repo. But i have a requirement to scan just specific files like ignoring .github files. For that FILTER_REGEX_INCLUDE: every time gives no files found message, i even committed new files and all to check.

workflow
https://github.com/missAnkita/Reusable-Workflows/blob/main/.github/workflows/super-linter-resuable-wf.yml

action
https://github.com/missAnkita/Reusable-Workflows/blob/main/.github/actions/Super-Linter/action.yml

caller:
https://github.com/missAnkita/azure_functions_app1/actions/workflows/caller.yml

**Comment by missAnkita** [comment]
for example when we set VALIDATE_ALL_CODEBASE: false it should lint the newly added or edited files but superlinter is not picking it up to lint and thus gives message like no files found to lint

**Comment by missAnkita** [comment]
Hi, please check and let me know

**Comment by ferrarimarco** [comment]
I think it's a matter of setting `FILTER_REGEX_INCLUDE` with the right regex.

Try with: `.*\.(cs|js|sh)$`

**Comment by missAnkita** [comment]
Hi, i tried,

I committed one new file named test.sh in source code repo. 

But it didn't get linted:

https://github.com/missAnkita/azure_functions_app1/actions/runs/10368590005/job/28702702112

Below is src code repo: 
https://github.com/missAnkita/azure_functions_app1/tree/master

super linter cnfig:
- name: Super Linter Code Base
        uses: missAnkita/Reusable-Workflows/.github/actions/Super-Linter@main
        env:
          FILTER_REGEX_INCLUDE: '.*\.(cs|js|sh)$'

**Comment by ferrarimarco** [comment]
I just noticed that you're using a quite old Super-linter version. I suggest switching to `v6.8.0` instead of `v5`, and try again. We fixed a lot of bugs since then.

**Comment by missAnkita** [comment]
But super linter v6.8.0 requires passing github token, but in my project i am not allowed to pass the same. That's why switched to old version. 

With latest version can i run super linter without token?

**Comment by ferrarimarco** [comment]
You can update to `v6.8.0`, and set `MULTI_STATUS` to `false` and Super-linter will not complain about a missing `GITHUB_TOKEN`.

**Comment by missAnkita** [comment]
Hi need one more helo, i want to ignore/exclude files under .github/ folder. But somehow checov picks up those files and it fails. 

- name: Super Linter Code Base
      uses: .github/actions/super-linter@feature/sl
      env:
          FILTER_REGEX_EXCLUDE: (^|/)\.github/.*
          MULTI_STATUS: false

could you please help here?

**Comment by missAnkita** [comment]
can you revert to me, its urgent

**Comment by ferrarimarco** [comment]
For how Checkov works, you would need to use its ignore feature because it expects to check entire modules and directories, not individual files.

You would need to specify the directories to lint or the ones to ignore in the Checkov configuration file.

**Comment by missAnkita** [comment]
- name: Super Linter Code Base
      uses: .github/actions/super-linter@feature/sl
      env:
          FILTER_REGEX_INCLUDE: .*\.(cs|js|sh|html)$
          #this is caller workflow which i don't want to lint inside .github/workflows/
          FILTER_REGEX_EXCLUDE: caller\.yml                       
          MULTI_STATUS: false

somehow super linter still lints all files, please check and let me know what's wrong here

**Comment by missAnkita** [comment]
env:
    FILTER_REGEX_INCLUDE: .*\.(cs|js|sh)$
    FILTER_REGEX_EXCLUDE: .*\.(html)$
    MULTI_STATUS: false

**Comment by missAnkita** [comment]
Hi, can you help please>


    - name: Super Linter Code Base
      uses: .github/actions/super-linter@feature/angular-deploy
      env:
          FILTER_REGEX_INCLUDE: .*\.(cs|js|sh)$
          FILTER_REGEX_EXCLUDE: .*\.(html)$      
          MULTI_STATUS: false

**Comment by ferrarimarco** [comment]
Hi! What you're trying to achieve is not entirely clear. Can you please:

1. Start using `super-linter/super-linter@v7.0.0` directly instead of a reusable workflow. Let's first have this working, then you can switch to a reusable workflow later.
2. Clearly list your requirements.
3. Post your entire workflow configuration, eventually redacting sensitive information.
4. Add a link to a workflow run with debug logging enabled.
