### ISSUE TITLE
Add support for nbqa for Jupyter Notebooks

### ISSUE THREAD

**Issue by holtskinner** [super-linter/super-linter#6171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Super Linter cannot lint Jupyter Notebooks

### Expected Behavior

Super Linter can perform linting on Jupyter Notebooks.

[nbqa](https://github.com/nbQA-dev/nbQA) is a tool that adds compatibility of Python linters for Jupyter notebooks

**Comment by ferrarimarco** [comment]
This is an interesting proposal. We'll happily review PRs about this.

Thanks for taking the time to send this idea!
