### ISSUE TITLE
Create issues for found errors

### ISSUE THREAD

**Issue by NormanTUD** [super-linter/super-linter#6268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have not found anything here yet. Love the plugin. But is it possible somehow to, for each error found in the files, open an issue and report the lines in there, and close it if it's fixed, like todo-to-issue. I'd love that!

**Comment by ferrarimarco** [comment]
Hi!

This is out of scope for this project. You might be able to implement something like this with other actions or by implementing your own script. Example: https://github.com/super-linter/super-linter/blob/7b76efbd69ef471b83d5273d4b5d8b3cbd8e5e3f/.github/workflows/cd.yml#L244-L258
