### ISSUE TITLE
npm-groovy-lint 15.0.2 fails with Jenkins shared library

### ISSUE THREAD

**Issue by yermulnik** [super-linter/super-linter#6371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Super-linter version available?

- [X] I am using the latest Super-linter version.
- [X] I can reproduce the issue running Super-linter using complete version identifier (example: vX.Y.Z), and not just with a partial one (example: vX)

- [X] I am using the super-linter/super-linter action or container image, and not the deprecated github/super-linter action or container image.

### Are you resonably sure that it's a Super-linter issue, and not an issue related to a tool that Super-linter runs?

- [ ] I think that this is a Super-linter issue.

### Current Behavior

Via https://github.com/super-linter/super-linter/pull/6266 the `npm-groovy-lint` was upgraded to `15.0.2` which has known and unresolved parsing issue with Jenkins shared library:
```
    0     error    Unknown parsing error: "/github/workspace/ami_build/Jenkinsfile: 2: unable to resolve class Library for annotation
   @ line 2, column 1.
     @Library('shared-library') _
     ^
  "  NglParseError
```
Please see:
* https://github.com/nvuillam/npm-groovy-lint/issues/422
* https://github.com/nvuillam/npm-groovy-lint/issues/428

Please downgrade `npm-groovy-lint` to `15.0.0` or lower. Thank you.

### Expected Behavior

`npm-groovy-lint` is downgraded unless the issue with Jenkins shared library is resolved.

### Super-Linter version

```markdown
2024-11-18 15:58:46 [INFO]   --- GitHub Actions Multi Language Linter ----
  2024-11-18 15:58:46 [INFO]    - Image Creation Date: 2024-11-18T13:53:56Z
  2024-11-18 15:58:46 [INFO]    - Image Revision: e1cb86b6e8d119f789513668b4b30bf17fe1efe4
  2024-11-18 15:58:46 [INFO]    - Image Version: 7.2.0
```

### Super-linter configuration

```yaml
`super-linter/super-linter/slim@v7`
```

### Relevant log output

```shell
0     error    Unknown parsing error: "/github/workspace/ami_build/Jenkinsfile: 2: unable to resolve class Library for annotation
   @ line 2, column 1.
     @Library('shared-library') _
     ^
  "  NglParseError
```

### Steps To Reproduce

Run latest `super-linter` on Jenkinsfile with `@Library('shared-library') _` import.

**Comment by ferrarimarco** [comment]
Hi! We should also add a test to ensure that we don't accidentally merge this update back.

**Comment by ferrarimarco** [comment]
@yermulnik Can you share an example Jenkinsfile that triggers this? So we can use that in the test. Thanks.

**Comment by ferrarimarco** [comment]
#6373 should take care of this.

**Comment by yermulnik** [comment]
> @yermulnik Can you share an example Jenkinsfile that triggers this? So we can use that in the test. Thanks.

```groovy
> head -5 ../ami_build/Jenkinsfile
@Library('shared-library') _

import java.time.LocalDateTime

Map buildConfig = [
```

**Comment by yermulnik** [comment]
So it's actually about that single `@Library...` line. The test file from https://github.com/super-linter/super-linter/pull/6373 should be good test case I guess.

**Comment by ferrarimarco** [comment]
Thanks!

**Comment by alexanderbazhenoff** [comment]
Still need `@Library` workaround. How to disable them in npm-groovy-lint v15.0.2?

**Comment by yermulnik** [comment]
FYI: https://github.com/super-linter/super-linter/issues/6600
