### ISSUE TITLE
Do we need to support a "lint directory" use case?

### ISSUE THREAD

**Issue by ferrarimarco** [super-linter/super-linter#888]
Currently, super-linter mainly focuses on linting single files, treating cases where a linter supports "whole" directories only as special/peculiar.

Instead of adding other special cases (`ansible-lint`, `jscpd`, we should plan for a more generalized `lint this whole directory` use case.

**Comment by GaboFDC** [comment]
This would be a really nice feature, there is some related issues also like #424, #736 and maybe others.
Problem is not sure what would be the logic to do so, if we pretend to do it auto-magically it.
We could also take the same approach as with ansible, and when the users wants to check a folder as a whole, allow it to do so via an ENV var, but this doesn't seems like the best.

**Comment by ferrarimarco** [comment]
I think most of the complexity will be where we build the file list. In fact, the other parts still continue to work as they are now.

In cases where we want to lint directories, we can automatically detect them if possible, so that a user doesn't have to specify them manually (in other words, remove the `ANSIBLE_DIRECTORY` variable). This would be consistent with what we do with other linters: for files, we have criteria to detect a file type (extension, content...).

For directories, I feel we should do the same.

**Comment by ferrarimarco** [comment]
PS: after we gather some consensus, I can give this a shot.

**Comment by MusaBack** [comment]
Ok I need jt thanks

**Comment by GaboFDC** [comment]
I'm just wondering what will be the criteria, or how you will determine which liter to use in what folder.
i.e. if there is a folder with 3 yml files, then what?
what if there are 2 ruby files and 2 yml?
what if there are 5 files from 5 different extensions?
what if the folder has 80% of one extension, 10% of other, and 10% of another one?
what if there is a folder with some files of one extension, then 3 folders, each with files from 3 diferent extensions?
That is the logic I mean would be the problem.
If you see a solution to this, or maybe i'm seeing it on the wrong way please share your feedback, but if you see it simplier or there is something i'm missing by all means give it a shot.

**Comment by MusaBack** [comment]
Fi nuW disk wuzic ould anw..ass I won’t o .. pl5

**Comment by ferrarimarco** [comment]
> I'm just wondering what will be the criteria, or how you will determine which liter to use in what folder.

> i.e. if there is a folder with 3 yml files, then what?
> what if there are 2 ruby files and 2 yml?
> what if there are 5 files from 5 different extensions?
> what if the folder has 80% of one extension, 10% of other, and 10% of another one?
> what if there is a folder with some files of one extension, then 3 folders, each with files from 3 diferent extensions?
> That is the logic I mean would be the problem.
> If you see a solution to this, or maybe i'm seeing it on the wrong way please share your feedback, but if you see it simplier or there is something i'm missing by all means give it a shot.

You might run different linters on in the same folder! The criteria would be easier than it seems, because it's already somewhat similar to what we're doing in the `DetectXXX` functions. In this case, we should look at the linter documentation to check what it looks for before linting. Example criteria for tfsec: Is there at least one terraform descriptor in that folder? Yes -> add it to the tfsec file list; no -> skip it.

We don't have to bother if there are other kind of files in that folder, because the logic to build the file list that we have now still applies. Example: if the aforementioned folder contains not only Terraform stuff, but also a shell script, that script is going to be linted by other linters as well (such as shellcheck). And this is ok, and expected.

**Comment by ferrarimarco** [comment]
I think we need to tackle this problem somehow, because there are significant discrepancies between `LintCodeBase` and `LintAnsibleFiles` (our only "lint directories" use case).

**Comment by GaboFDC** [comment]
So, if I get it correctly, yo sai, that we check a file in a dir, and then depending on the type of that file, we add the parent dir, to be linted as a whole?

And what controls when to lint a dir and when to lint a file? We leave to user choice by a flag? or do you think there is a way we can detect automatically?

**Comment by ferrarimarco** [comment]
I don't see that complexity because linting a file or a directory with a linter doesn't prevent you from linting the same file or directory with another linter. We're already doing this. For example:

1. YAML files are linted against multiple linters already (yamllint and kubeval if the yaml is also a Kubernetes descriptor, and possibly others)
1. editorconfig-checker lints every text file, and then we lint the same files with other linters.

So I was thinking more about something like a refinement of our scanning logic. We currently deal with files only, adding a file to (possibly multiple) file lists, according to its extension, type, and contents. What I propose is adding logic to do the same with directories. Example: is this directory an ansible role? -> add it to the directories to be linted with ansible-lint.

Since we already have `ansible-lint` on board, and might be others in the future, we might want to think about a possible implementation of this use case. Note that we're already doing this, because we're using `LintAnsibleFiles`, instead of `LintCodeBase`.

Backstory: when refactoring the code base to remove duplicate code, I originally thought to get rid of the `LintAnsibleFiles` function and add its logic to `LintCodeBase` as an exception. And we got #886, which asked for the very same feature but for `tfsec`.

We might still abandon the idea of a `lint directory` use case, but we've to make `LintAnsibleFiles` use the same logic we're using in `LintCodeBase`, and think about how to add linters that work on directories instead of files, in a scalable way.

**Comment by GaboFDC** [comment]
I'm in favor of this, I was just a bit lost on how you planned to do it. But seems like you have the idea pretty clear. Maybe I saw it more complicated that it actually is. Go for it 👍

**Comment by ferrarimarco** [comment]
#1035 takes care of getting rid of the `LintAnsibleFiles` function.

**Comment by zkoppert** [comment]
@Hanse00 I see that you reopened this one. What work still needs to be done here? Does https://github.com/super-linter/super-linter/pull/1035 not cover closing this issue? Just looking for some more info so we can try and move towards completing this one.

**Comment by ferrarimarco** [comment]
After additional consideration, we realized that the infrastructure already supports this when we can correctly identify the contents of a directory.
